// Code generated by radius-dict-gen. DO NOT EDIT.

package fortinet

import (
	"net"
	"time"

	"layeh.com/radius"
	"layeh.com/radius/rfc2865"
)

const (
	_Fortinet_VendorID = 12356
)

func _Fortinet_AddVendor(p *radius.Packet, typ byte, attr radius.Attribute) (err error) {
	var vsa radius.Attribute
	vendor := make(radius.Attribute, 2+len(attr))
	vendor[0] = typ
	vendor[1] = byte(len(vendor))
	copy(vendor[2:], attr)
	vsa, err = radius.NewVendorSpecific(_Fortinet_VendorID, vendor)
	if err != nil {
		return
	}
	p.Add(rfc2865.VendorSpecific_Type, vsa)
	return
}

func _Fortinet_GetsVendor(p *radius.Packet, typ byte) (values []radius.Attribute) {
	for _, avp := range p.Attributes {
		if avp.Type != rfc2865.VendorSpecific_Type {
			continue
		}
		attr := avp.Attribute
		vendorID, vsa, err := radius.VendorSpecific(attr)
		if err != nil || vendorID != _Fortinet_VendorID {
			continue
		}
		for len(vsa) >= 3 {
			vsaTyp, vsaLen := vsa[0], vsa[1]
			if int(vsaLen) > len(vsa) || vsaLen < 3 {
				break
			}
			if vsaTyp == typ {
				values = append(values, vsa[2:int(vsaLen)])
			}
			vsa = vsa[int(vsaLen):]
		}
	}
	return
}

func _Fortinet_LookupVendor(p *radius.Packet, typ byte) (attr radius.Attribute, ok bool) {
	for _, avp := range p.Attributes {
		if avp.Type != rfc2865.VendorSpecific_Type {
			continue
		}
		attr := avp.Attribute
		vendorID, vsa, err := radius.VendorSpecific(attr)
		if err != nil || vendorID != _Fortinet_VendorID {
			continue
		}
		for len(vsa) >= 3 {
			vsaTyp, vsaLen := vsa[0], vsa[1]
			if int(vsaLen) > len(vsa) || vsaLen < 3 {
				break
			}
			if vsaTyp == typ {
				return vsa[2:int(vsaLen)], true
			}
			vsa = vsa[int(vsaLen):]
		}
	}
	return
}

func _Fortinet_SetVendor(p *radius.Packet, typ byte, attr radius.Attribute) (err error) {
	for i := 0; i < len(p.Attributes); {
		avp := p.Attributes[i]
		if avp.Type != rfc2865.VendorSpecific_Type {
			i++
			continue
		}
		vendorID, vsa, err := radius.VendorSpecific(avp.Attribute)
		if err != nil || vendorID != _Fortinet_VendorID {
			i++
			continue
		}
		for j := 0; len(vsa[j:]) >= 3; {
			vsaTyp, vsaLen := vsa[0], vsa[1]
			if int(vsaLen) > len(vsa[j:]) || vsaLen < 3 {
				i++
				break
			}
			if vsaTyp == typ {
				vsa = append(vsa[:j], vsa[j+int(vsaLen):]...)
			}
			j += int(vsaLen)
		}
		if len(vsa) > 0 {
			copy(avp.Attribute[4:], vsa)
			i++
		} else {
			p.Attributes = append(p.Attributes[:i], p.Attributes[i+i:]...)
		}
	}
	return _Fortinet_AddVendor(p, typ, attr)
}

func _Fortinet_DelVendor(p *radius.Packet, typ byte) {
vsaLoop:
	for i := 0; i < len(p.Attributes); {
		avp := p.Attributes[i]
		if avp.Type != rfc2865.VendorSpecific_Type {
			i++
			continue
		}
		vendorID, vsa, err := radius.VendorSpecific(avp.Attribute)
		if err != nil || vendorID != _Fortinet_VendorID {
			i++
			continue
		}
		offset := 0
		for len(vsa[offset:]) >= 3 {
			vsaTyp, vsaLen := vsa[offset], vsa[offset+1]
			if int(vsaLen) > len(vsa) || vsaLen < 3 {
				continue vsaLoop
			}
			if vsaTyp == typ {
				copy(vsa[offset:], vsa[offset+int(vsaLen):])
				vsa = vsa[:len(vsa)-int(vsaLen)]
			} else {
				offset += int(vsaLen)
			}
		}
		if offset == 0 {
			p.Attributes = append(p.Attributes[:i], p.Attributes[i+1:]...)
		} else {
			i++
		}
	}
	return
}

func GroupName_Add(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Fortinet_AddVendor(p, 1, a)
}

func GroupName_AddString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Fortinet_AddVendor(p, 1, a)
}

func GroupName_Get(p *radius.Packet) (value []byte) {
	value, _ = GroupName_Lookup(p)
	return
}

func GroupName_GetString(p *radius.Packet) (value string) {
	value, _ = GroupName_LookupString(p)
	return
}

func GroupName_Gets(p *radius.Packet) (values [][]byte, err error) {
	var i []byte
	for _, attr := range _Fortinet_GetsVendor(p, 1) {
		i = radius.Bytes(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func GroupName_GetStrings(p *radius.Packet) (values []string, err error) {
	var i string
	for _, attr := range _Fortinet_GetsVendor(p, 1) {
		i = radius.String(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func GroupName_Lookup(p *radius.Packet) (value []byte, err error) {
	a, ok := _Fortinet_LookupVendor(p, 1)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.Bytes(a)
	return
}

func GroupName_LookupString(p *radius.Packet) (value string, err error) {
	a, ok := _Fortinet_LookupVendor(p, 1)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.String(a)
	return
}

func GroupName_Set(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Fortinet_SetVendor(p, 1, a)
}

func GroupName_SetString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Fortinet_SetVendor(p, 1, a)
}

func GroupName_Del(p *radius.Packet) {
	_Fortinet_DelVendor(p, 1)
}

func ClientIPAddress_Add(p *radius.Packet, value net.IP) (err error) {
	var a radius.Attribute
	a, err = radius.NewIPAddr(value)
	if err != nil {
		return
	}
	return _Fortinet_AddVendor(p, 2, a)
}

func ClientIPAddress_Get(p *radius.Packet) (value net.IP) {
	value, _ = ClientIPAddress_Lookup(p)
	return
}

func ClientIPAddress_Gets(p *radius.Packet) (values []net.IP, err error) {
	var i net.IP
	for _, attr := range _Fortinet_GetsVendor(p, 2) {
		i, err = radius.IPAddr(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func ClientIPAddress_Lookup(p *radius.Packet) (value net.IP, err error) {
	a, ok := _Fortinet_LookupVendor(p, 2)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value, err = radius.IPAddr(a)
	return
}

func ClientIPAddress_Set(p *radius.Packet, value net.IP) (err error) {
	var a radius.Attribute
	a, err = radius.NewIPAddr(value)
	if err != nil {
		return
	}
	return _Fortinet_SetVendor(p, 2, a)
}

func ClientIPAddress_Del(p *radius.Packet) {
	_Fortinet_DelVendor(p, 2)
}

func VdomName_Add(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Fortinet_AddVendor(p, 3, a)
}

func VdomName_AddString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Fortinet_AddVendor(p, 3, a)
}

func VdomName_Get(p *radius.Packet) (value []byte) {
	value, _ = VdomName_Lookup(p)
	return
}

func VdomName_GetString(p *radius.Packet) (value string) {
	value, _ = VdomName_LookupString(p)
	return
}

func VdomName_Gets(p *radius.Packet) (values [][]byte, err error) {
	var i []byte
	for _, attr := range _Fortinet_GetsVendor(p, 3) {
		i = radius.Bytes(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func VdomName_GetStrings(p *radius.Packet) (values []string, err error) {
	var i string
	for _, attr := range _Fortinet_GetsVendor(p, 3) {
		i = radius.String(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func VdomName_Lookup(p *radius.Packet) (value []byte, err error) {
	a, ok := _Fortinet_LookupVendor(p, 3)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.Bytes(a)
	return
}

func VdomName_LookupString(p *radius.Packet) (value string, err error) {
	a, ok := _Fortinet_LookupVendor(p, 3)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.String(a)
	return
}

func VdomName_Set(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Fortinet_SetVendor(p, 3, a)
}

func VdomName_SetString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Fortinet_SetVendor(p, 3, a)
}

func VdomName_Del(p *radius.Packet) {
	_Fortinet_DelVendor(p, 3)
}

func ClientIPv6Address_Add(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Fortinet_AddVendor(p, 4, a)
}

func ClientIPv6Address_AddString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Fortinet_AddVendor(p, 4, a)
}

func ClientIPv6Address_Get(p *radius.Packet) (value []byte) {
	value, _ = ClientIPv6Address_Lookup(p)
	return
}

func ClientIPv6Address_GetString(p *radius.Packet) (value string) {
	value, _ = ClientIPv6Address_LookupString(p)
	return
}

func ClientIPv6Address_Gets(p *radius.Packet) (values [][]byte, err error) {
	var i []byte
	for _, attr := range _Fortinet_GetsVendor(p, 4) {
		i = radius.Bytes(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func ClientIPv6Address_GetStrings(p *radius.Packet) (values []string, err error) {
	var i string
	for _, attr := range _Fortinet_GetsVendor(p, 4) {
		i = radius.String(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func ClientIPv6Address_Lookup(p *radius.Packet) (value []byte, err error) {
	a, ok := _Fortinet_LookupVendor(p, 4)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.Bytes(a)
	return
}

func ClientIPv6Address_LookupString(p *radius.Packet) (value string, err error) {
	a, ok := _Fortinet_LookupVendor(p, 4)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.String(a)
	return
}

func ClientIPv6Address_Set(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Fortinet_SetVendor(p, 4, a)
}

func ClientIPv6Address_SetString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Fortinet_SetVendor(p, 4, a)
}

func ClientIPv6Address_Del(p *radius.Packet) {
	_Fortinet_DelVendor(p, 4)
}

func InterfaceName_Add(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Fortinet_AddVendor(p, 5, a)
}

func InterfaceName_AddString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Fortinet_AddVendor(p, 5, a)
}

func InterfaceName_Get(p *radius.Packet) (value []byte) {
	value, _ = InterfaceName_Lookup(p)
	return
}

func InterfaceName_GetString(p *radius.Packet) (value string) {
	value, _ = InterfaceName_LookupString(p)
	return
}

func InterfaceName_Gets(p *radius.Packet) (values [][]byte, err error) {
	var i []byte
	for _, attr := range _Fortinet_GetsVendor(p, 5) {
		i = radius.Bytes(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func InterfaceName_GetStrings(p *radius.Packet) (values []string, err error) {
	var i string
	for _, attr := range _Fortinet_GetsVendor(p, 5) {
		i = radius.String(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func InterfaceName_Lookup(p *radius.Packet) (value []byte, err error) {
	a, ok := _Fortinet_LookupVendor(p, 5)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.Bytes(a)
	return
}

func InterfaceName_LookupString(p *radius.Packet) (value string, err error) {
	a, ok := _Fortinet_LookupVendor(p, 5)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.String(a)
	return
}

func InterfaceName_Set(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Fortinet_SetVendor(p, 5, a)
}

func InterfaceName_SetString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Fortinet_SetVendor(p, 5, a)
}

func InterfaceName_Del(p *radius.Packet) {
	_Fortinet_DelVendor(p, 5)
}

func AccessProfile_Add(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Fortinet_AddVendor(p, 6, a)
}

func AccessProfile_AddString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Fortinet_AddVendor(p, 6, a)
}

func AccessProfile_Get(p *radius.Packet) (value []byte) {
	value, _ = AccessProfile_Lookup(p)
	return
}

func AccessProfile_GetString(p *radius.Packet) (value string) {
	value, _ = AccessProfile_LookupString(p)
	return
}

func AccessProfile_Gets(p *radius.Packet) (values [][]byte, err error) {
	var i []byte
	for _, attr := range _Fortinet_GetsVendor(p, 6) {
		i = radius.Bytes(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func AccessProfile_GetStrings(p *radius.Packet) (values []string, err error) {
	var i string
	for _, attr := range _Fortinet_GetsVendor(p, 6) {
		i = radius.String(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func AccessProfile_Lookup(p *radius.Packet) (value []byte, err error) {
	a, ok := _Fortinet_LookupVendor(p, 6)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.Bytes(a)
	return
}

func AccessProfile_LookupString(p *radius.Packet) (value string, err error) {
	a, ok := _Fortinet_LookupVendor(p, 6)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.String(a)
	return
}

func AccessProfile_Set(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Fortinet_SetVendor(p, 6, a)
}

func AccessProfile_SetString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Fortinet_SetVendor(p, 6, a)
}

func AccessProfile_Del(p *radius.Packet) {
	_Fortinet_DelVendor(p, 6)
}

func SSID_Add(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Fortinet_AddVendor(p, 7, a)
}

func SSID_AddString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Fortinet_AddVendor(p, 7, a)
}

func SSID_Get(p *radius.Packet) (value []byte) {
	value, _ = SSID_Lookup(p)
	return
}

func SSID_GetString(p *radius.Packet) (value string) {
	value, _ = SSID_LookupString(p)
	return
}

func SSID_Gets(p *radius.Packet) (values [][]byte, err error) {
	var i []byte
	for _, attr := range _Fortinet_GetsVendor(p, 7) {
		i = radius.Bytes(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func SSID_GetStrings(p *radius.Packet) (values []string, err error) {
	var i string
	for _, attr := range _Fortinet_GetsVendor(p, 7) {
		i = radius.String(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func SSID_Lookup(p *radius.Packet) (value []byte, err error) {
	a, ok := _Fortinet_LookupVendor(p, 7)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.Bytes(a)
	return
}

func SSID_LookupString(p *radius.Packet) (value string, err error) {
	a, ok := _Fortinet_LookupVendor(p, 7)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.String(a)
	return
}

func SSID_Set(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Fortinet_SetVendor(p, 7, a)
}

func SSID_SetString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Fortinet_SetVendor(p, 7, a)
}

func SSID_Del(p *radius.Packet) {
	_Fortinet_DelVendor(p, 7)
}

func APName_Add(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Fortinet_AddVendor(p, 8, a)
}

func APName_AddString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Fortinet_AddVendor(p, 8, a)
}

func APName_Get(p *radius.Packet) (value []byte) {
	value, _ = APName_Lookup(p)
	return
}

func APName_GetString(p *radius.Packet) (value string) {
	value, _ = APName_LookupString(p)
	return
}

func APName_Gets(p *radius.Packet) (values [][]byte, err error) {
	var i []byte
	for _, attr := range _Fortinet_GetsVendor(p, 8) {
		i = radius.Bytes(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func APName_GetStrings(p *radius.Packet) (values []string, err error) {
	var i string
	for _, attr := range _Fortinet_GetsVendor(p, 8) {
		i = radius.String(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func APName_Lookup(p *radius.Packet) (value []byte, err error) {
	a, ok := _Fortinet_LookupVendor(p, 8)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.Bytes(a)
	return
}

func APName_LookupString(p *radius.Packet) (value string, err error) {
	a, ok := _Fortinet_LookupVendor(p, 8)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.String(a)
	return
}

func APName_Set(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Fortinet_SetVendor(p, 8, a)
}

func APName_SetString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Fortinet_SetVendor(p, 8, a)
}

func APName_Del(p *radius.Packet) {
	_Fortinet_DelVendor(p, 8)
}

func FACAuthStatus_Add(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Fortinet_AddVendor(p, 11, a)
}

func FACAuthStatus_AddString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Fortinet_AddVendor(p, 11, a)
}

func FACAuthStatus_Get(p *radius.Packet) (value []byte) {
	value, _ = FACAuthStatus_Lookup(p)
	return
}

func FACAuthStatus_GetString(p *radius.Packet) (value string) {
	value, _ = FACAuthStatus_LookupString(p)
	return
}

func FACAuthStatus_Gets(p *radius.Packet) (values [][]byte, err error) {
	var i []byte
	for _, attr := range _Fortinet_GetsVendor(p, 11) {
		i = radius.Bytes(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func FACAuthStatus_GetStrings(p *radius.Packet) (values []string, err error) {
	var i string
	for _, attr := range _Fortinet_GetsVendor(p, 11) {
		i = radius.String(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func FACAuthStatus_Lookup(p *radius.Packet) (value []byte, err error) {
	a, ok := _Fortinet_LookupVendor(p, 11)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.Bytes(a)
	return
}

func FACAuthStatus_LookupString(p *radius.Packet) (value string, err error) {
	a, ok := _Fortinet_LookupVendor(p, 11)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.String(a)
	return
}

func FACAuthStatus_Set(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Fortinet_SetVendor(p, 11, a)
}

func FACAuthStatus_SetString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Fortinet_SetVendor(p, 11, a)
}

func FACAuthStatus_Del(p *radius.Packet) {
	_Fortinet_DelVendor(p, 11)
}

func FACTokenID_Add(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Fortinet_AddVendor(p, 12, a)
}

func FACTokenID_AddString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Fortinet_AddVendor(p, 12, a)
}

func FACTokenID_Get(p *radius.Packet) (value []byte) {
	value, _ = FACTokenID_Lookup(p)
	return
}

func FACTokenID_GetString(p *radius.Packet) (value string) {
	value, _ = FACTokenID_LookupString(p)
	return
}

func FACTokenID_Gets(p *radius.Packet) (values [][]byte, err error) {
	var i []byte
	for _, attr := range _Fortinet_GetsVendor(p, 12) {
		i = radius.Bytes(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func FACTokenID_GetStrings(p *radius.Packet) (values []string, err error) {
	var i string
	for _, attr := range _Fortinet_GetsVendor(p, 12) {
		i = radius.String(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func FACTokenID_Lookup(p *radius.Packet) (value []byte, err error) {
	a, ok := _Fortinet_LookupVendor(p, 12)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.Bytes(a)
	return
}

func FACTokenID_LookupString(p *radius.Packet) (value string, err error) {
	a, ok := _Fortinet_LookupVendor(p, 12)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.String(a)
	return
}

func FACTokenID_Set(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Fortinet_SetVendor(p, 12, a)
}

func FACTokenID_SetString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Fortinet_SetVendor(p, 12, a)
}

func FACTokenID_Del(p *radius.Packet) {
	_Fortinet_DelVendor(p, 12)
}

func FACChallengeCode_Add(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Fortinet_AddVendor(p, 15, a)
}

func FACChallengeCode_AddString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Fortinet_AddVendor(p, 15, a)
}

func FACChallengeCode_Get(p *radius.Packet) (value []byte) {
	value, _ = FACChallengeCode_Lookup(p)
	return
}

func FACChallengeCode_GetString(p *radius.Packet) (value string) {
	value, _ = FACChallengeCode_LookupString(p)
	return
}

func FACChallengeCode_Gets(p *radius.Packet) (values [][]byte, err error) {
	var i []byte
	for _, attr := range _Fortinet_GetsVendor(p, 15) {
		i = radius.Bytes(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func FACChallengeCode_GetStrings(p *radius.Packet) (values []string, err error) {
	var i string
	for _, attr := range _Fortinet_GetsVendor(p, 15) {
		i = radius.String(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func FACChallengeCode_Lookup(p *radius.Packet) (value []byte, err error) {
	a, ok := _Fortinet_LookupVendor(p, 15)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.Bytes(a)
	return
}

func FACChallengeCode_LookupString(p *radius.Packet) (value string, err error) {
	a, ok := _Fortinet_LookupVendor(p, 15)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.String(a)
	return
}

func FACChallengeCode_Set(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Fortinet_SetVendor(p, 15, a)
}

func FACChallengeCode_SetString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Fortinet_SetVendor(p, 15, a)
}

func FACChallengeCode_Del(p *radius.Packet) {
	_Fortinet_DelVendor(p, 15)
}

func WebfilterCategoryAllow_Add(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Fortinet_AddVendor(p, 16, a)
}

func WebfilterCategoryAllow_AddString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Fortinet_AddVendor(p, 16, a)
}

func WebfilterCategoryAllow_Get(p *radius.Packet) (value []byte) {
	value, _ = WebfilterCategoryAllow_Lookup(p)
	return
}

func WebfilterCategoryAllow_GetString(p *radius.Packet) (value string) {
	value, _ = WebfilterCategoryAllow_LookupString(p)
	return
}

func WebfilterCategoryAllow_Gets(p *radius.Packet) (values [][]byte, err error) {
	var i []byte
	for _, attr := range _Fortinet_GetsVendor(p, 16) {
		i = radius.Bytes(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func WebfilterCategoryAllow_GetStrings(p *radius.Packet) (values []string, err error) {
	var i string
	for _, attr := range _Fortinet_GetsVendor(p, 16) {
		i = radius.String(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func WebfilterCategoryAllow_Lookup(p *radius.Packet) (value []byte, err error) {
	a, ok := _Fortinet_LookupVendor(p, 16)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.Bytes(a)
	return
}

func WebfilterCategoryAllow_LookupString(p *radius.Packet) (value string, err error) {
	a, ok := _Fortinet_LookupVendor(p, 16)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.String(a)
	return
}

func WebfilterCategoryAllow_Set(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Fortinet_SetVendor(p, 16, a)
}

func WebfilterCategoryAllow_SetString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Fortinet_SetVendor(p, 16, a)
}

func WebfilterCategoryAllow_Del(p *radius.Packet) {
	_Fortinet_DelVendor(p, 16)
}

func WebfilterCategoryBlock_Add(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Fortinet_AddVendor(p, 17, a)
}

func WebfilterCategoryBlock_AddString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Fortinet_AddVendor(p, 17, a)
}

func WebfilterCategoryBlock_Get(p *radius.Packet) (value []byte) {
	value, _ = WebfilterCategoryBlock_Lookup(p)
	return
}

func WebfilterCategoryBlock_GetString(p *radius.Packet) (value string) {
	value, _ = WebfilterCategoryBlock_LookupString(p)
	return
}

func WebfilterCategoryBlock_Gets(p *radius.Packet) (values [][]byte, err error) {
	var i []byte
	for _, attr := range _Fortinet_GetsVendor(p, 17) {
		i = radius.Bytes(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func WebfilterCategoryBlock_GetStrings(p *radius.Packet) (values []string, err error) {
	var i string
	for _, attr := range _Fortinet_GetsVendor(p, 17) {
		i = radius.String(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func WebfilterCategoryBlock_Lookup(p *radius.Packet) (value []byte, err error) {
	a, ok := _Fortinet_LookupVendor(p, 17)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.Bytes(a)
	return
}

func WebfilterCategoryBlock_LookupString(p *radius.Packet) (value string, err error) {
	a, ok := _Fortinet_LookupVendor(p, 17)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.String(a)
	return
}

func WebfilterCategoryBlock_Set(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Fortinet_SetVendor(p, 17, a)
}

func WebfilterCategoryBlock_SetString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Fortinet_SetVendor(p, 17, a)
}

func WebfilterCategoryBlock_Del(p *radius.Packet) {
	_Fortinet_DelVendor(p, 17)
}

func WebfilterCategoryMonitor_Add(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Fortinet_AddVendor(p, 18, a)
}

func WebfilterCategoryMonitor_AddString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Fortinet_AddVendor(p, 18, a)
}

func WebfilterCategoryMonitor_Get(p *radius.Packet) (value []byte) {
	value, _ = WebfilterCategoryMonitor_Lookup(p)
	return
}

func WebfilterCategoryMonitor_GetString(p *radius.Packet) (value string) {
	value, _ = WebfilterCategoryMonitor_LookupString(p)
	return
}

func WebfilterCategoryMonitor_Gets(p *radius.Packet) (values [][]byte, err error) {
	var i []byte
	for _, attr := range _Fortinet_GetsVendor(p, 18) {
		i = radius.Bytes(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func WebfilterCategoryMonitor_GetStrings(p *radius.Packet) (values []string, err error) {
	var i string
	for _, attr := range _Fortinet_GetsVendor(p, 18) {
		i = radius.String(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func WebfilterCategoryMonitor_Lookup(p *radius.Packet) (value []byte, err error) {
	a, ok := _Fortinet_LookupVendor(p, 18)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.Bytes(a)
	return
}

func WebfilterCategoryMonitor_LookupString(p *radius.Packet) (value string, err error) {
	a, ok := _Fortinet_LookupVendor(p, 18)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.String(a)
	return
}

func WebfilterCategoryMonitor_Set(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Fortinet_SetVendor(p, 18, a)
}

func WebfilterCategoryMonitor_SetString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Fortinet_SetVendor(p, 18, a)
}

func WebfilterCategoryMonitor_Del(p *radius.Packet) {
	_Fortinet_DelVendor(p, 18)
}

func AppCtrlCategoryAllow_Add(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Fortinet_AddVendor(p, 19, a)
}

func AppCtrlCategoryAllow_AddString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Fortinet_AddVendor(p, 19, a)
}

func AppCtrlCategoryAllow_Get(p *radius.Packet) (value []byte) {
	value, _ = AppCtrlCategoryAllow_Lookup(p)
	return
}

func AppCtrlCategoryAllow_GetString(p *radius.Packet) (value string) {
	value, _ = AppCtrlCategoryAllow_LookupString(p)
	return
}

func AppCtrlCategoryAllow_Gets(p *radius.Packet) (values [][]byte, err error) {
	var i []byte
	for _, attr := range _Fortinet_GetsVendor(p, 19) {
		i = radius.Bytes(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func AppCtrlCategoryAllow_GetStrings(p *radius.Packet) (values []string, err error) {
	var i string
	for _, attr := range _Fortinet_GetsVendor(p, 19) {
		i = radius.String(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func AppCtrlCategoryAllow_Lookup(p *radius.Packet) (value []byte, err error) {
	a, ok := _Fortinet_LookupVendor(p, 19)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.Bytes(a)
	return
}

func AppCtrlCategoryAllow_LookupString(p *radius.Packet) (value string, err error) {
	a, ok := _Fortinet_LookupVendor(p, 19)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.String(a)
	return
}

func AppCtrlCategoryAllow_Set(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Fortinet_SetVendor(p, 19, a)
}

func AppCtrlCategoryAllow_SetString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Fortinet_SetVendor(p, 19, a)
}

func AppCtrlCategoryAllow_Del(p *radius.Packet) {
	_Fortinet_DelVendor(p, 19)
}

func AppCtrlCategoryBlock_Add(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Fortinet_AddVendor(p, 20, a)
}

func AppCtrlCategoryBlock_AddString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Fortinet_AddVendor(p, 20, a)
}

func AppCtrlCategoryBlock_Get(p *radius.Packet) (value []byte) {
	value, _ = AppCtrlCategoryBlock_Lookup(p)
	return
}

func AppCtrlCategoryBlock_GetString(p *radius.Packet) (value string) {
	value, _ = AppCtrlCategoryBlock_LookupString(p)
	return
}

func AppCtrlCategoryBlock_Gets(p *radius.Packet) (values [][]byte, err error) {
	var i []byte
	for _, attr := range _Fortinet_GetsVendor(p, 20) {
		i = radius.Bytes(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func AppCtrlCategoryBlock_GetStrings(p *radius.Packet) (values []string, err error) {
	var i string
	for _, attr := range _Fortinet_GetsVendor(p, 20) {
		i = radius.String(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func AppCtrlCategoryBlock_Lookup(p *radius.Packet) (value []byte, err error) {
	a, ok := _Fortinet_LookupVendor(p, 20)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.Bytes(a)
	return
}

func AppCtrlCategoryBlock_LookupString(p *radius.Packet) (value string, err error) {
	a, ok := _Fortinet_LookupVendor(p, 20)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.String(a)
	return
}

func AppCtrlCategoryBlock_Set(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Fortinet_SetVendor(p, 20, a)
}

func AppCtrlCategoryBlock_SetString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Fortinet_SetVendor(p, 20, a)
}

func AppCtrlCategoryBlock_Del(p *radius.Packet) {
	_Fortinet_DelVendor(p, 20)
}

func AppCtrlRiskAllow_Add(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Fortinet_AddVendor(p, 21, a)
}

func AppCtrlRiskAllow_AddString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Fortinet_AddVendor(p, 21, a)
}

func AppCtrlRiskAllow_Get(p *radius.Packet) (value []byte) {
	value, _ = AppCtrlRiskAllow_Lookup(p)
	return
}

func AppCtrlRiskAllow_GetString(p *radius.Packet) (value string) {
	value, _ = AppCtrlRiskAllow_LookupString(p)
	return
}

func AppCtrlRiskAllow_Gets(p *radius.Packet) (values [][]byte, err error) {
	var i []byte
	for _, attr := range _Fortinet_GetsVendor(p, 21) {
		i = radius.Bytes(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func AppCtrlRiskAllow_GetStrings(p *radius.Packet) (values []string, err error) {
	var i string
	for _, attr := range _Fortinet_GetsVendor(p, 21) {
		i = radius.String(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func AppCtrlRiskAllow_Lookup(p *radius.Packet) (value []byte, err error) {
	a, ok := _Fortinet_LookupVendor(p, 21)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.Bytes(a)
	return
}

func AppCtrlRiskAllow_LookupString(p *radius.Packet) (value string, err error) {
	a, ok := _Fortinet_LookupVendor(p, 21)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.String(a)
	return
}

func AppCtrlRiskAllow_Set(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Fortinet_SetVendor(p, 21, a)
}

func AppCtrlRiskAllow_SetString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Fortinet_SetVendor(p, 21, a)
}

func AppCtrlRiskAllow_Del(p *radius.Packet) {
	_Fortinet_DelVendor(p, 21)
}

func AppCtrlRiskBlock_Add(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Fortinet_AddVendor(p, 22, a)
}

func AppCtrlRiskBlock_AddString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Fortinet_AddVendor(p, 22, a)
}

func AppCtrlRiskBlock_Get(p *radius.Packet) (value []byte) {
	value, _ = AppCtrlRiskBlock_Lookup(p)
	return
}

func AppCtrlRiskBlock_GetString(p *radius.Packet) (value string) {
	value, _ = AppCtrlRiskBlock_LookupString(p)
	return
}

func AppCtrlRiskBlock_Gets(p *radius.Packet) (values [][]byte, err error) {
	var i []byte
	for _, attr := range _Fortinet_GetsVendor(p, 22) {
		i = radius.Bytes(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func AppCtrlRiskBlock_GetStrings(p *radius.Packet) (values []string, err error) {
	var i string
	for _, attr := range _Fortinet_GetsVendor(p, 22) {
		i = radius.String(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func AppCtrlRiskBlock_Lookup(p *radius.Packet) (value []byte, err error) {
	a, ok := _Fortinet_LookupVendor(p, 22)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.Bytes(a)
	return
}

func AppCtrlRiskBlock_LookupString(p *radius.Packet) (value string, err error) {
	a, ok := _Fortinet_LookupVendor(p, 22)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.String(a)
	return
}

func AppCtrlRiskBlock_Set(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Fortinet_SetVendor(p, 22, a)
}

func AppCtrlRiskBlock_SetString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Fortinet_SetVendor(p, 22, a)
}

func AppCtrlRiskBlock_Del(p *radius.Packet) {
	_Fortinet_DelVendor(p, 22)
}

func WirelessControllerDeviceMAC_Add(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Fortinet_AddVendor(p, 23, a)
}

func WirelessControllerDeviceMAC_AddString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Fortinet_AddVendor(p, 23, a)
}

func WirelessControllerDeviceMAC_Get(p *radius.Packet) (value []byte) {
	value, _ = WirelessControllerDeviceMAC_Lookup(p)
	return
}

func WirelessControllerDeviceMAC_GetString(p *radius.Packet) (value string) {
	value, _ = WirelessControllerDeviceMAC_LookupString(p)
	return
}

func WirelessControllerDeviceMAC_Gets(p *radius.Packet) (values [][]byte, err error) {
	var i []byte
	for _, attr := range _Fortinet_GetsVendor(p, 23) {
		i = radius.Bytes(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func WirelessControllerDeviceMAC_GetStrings(p *radius.Packet) (values []string, err error) {
	var i string
	for _, attr := range _Fortinet_GetsVendor(p, 23) {
		i = radius.String(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func WirelessControllerDeviceMAC_Lookup(p *radius.Packet) (value []byte, err error) {
	a, ok := _Fortinet_LookupVendor(p, 23)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.Bytes(a)
	return
}

func WirelessControllerDeviceMAC_LookupString(p *radius.Packet) (value string, err error) {
	a, ok := _Fortinet_LookupVendor(p, 23)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.String(a)
	return
}

func WirelessControllerDeviceMAC_Set(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Fortinet_SetVendor(p, 23, a)
}

func WirelessControllerDeviceMAC_SetString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Fortinet_SetVendor(p, 23, a)
}

func WirelessControllerDeviceMAC_Del(p *radius.Packet) {
	_Fortinet_DelVendor(p, 23)
}

func WirelessControllerWTPID_Add(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Fortinet_AddVendor(p, 24, a)
}

func WirelessControllerWTPID_AddString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Fortinet_AddVendor(p, 24, a)
}

func WirelessControllerWTPID_Get(p *radius.Packet) (value []byte) {
	value, _ = WirelessControllerWTPID_Lookup(p)
	return
}

func WirelessControllerWTPID_GetString(p *radius.Packet) (value string) {
	value, _ = WirelessControllerWTPID_LookupString(p)
	return
}

func WirelessControllerWTPID_Gets(p *radius.Packet) (values [][]byte, err error) {
	var i []byte
	for _, attr := range _Fortinet_GetsVendor(p, 24) {
		i = radius.Bytes(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func WirelessControllerWTPID_GetStrings(p *radius.Packet) (values []string, err error) {
	var i string
	for _, attr := range _Fortinet_GetsVendor(p, 24) {
		i = radius.String(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func WirelessControllerWTPID_Lookup(p *radius.Packet) (value []byte, err error) {
	a, ok := _Fortinet_LookupVendor(p, 24)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.Bytes(a)
	return
}

func WirelessControllerWTPID_LookupString(p *radius.Packet) (value string, err error) {
	a, ok := _Fortinet_LookupVendor(p, 24)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.String(a)
	return
}

func WirelessControllerWTPID_Set(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Fortinet_SetVendor(p, 24, a)
}

func WirelessControllerWTPID_SetString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Fortinet_SetVendor(p, 24, a)
}

func WirelessControllerWTPID_Del(p *radius.Packet) {
	_Fortinet_DelVendor(p, 24)
}

func WirelessControllerAssocTime_Add(p *radius.Packet, value time.Time) (err error) {
	var a radius.Attribute
	a, err = radius.NewDate(value)
	if err != nil {
		return
	}
	return _Fortinet_AddVendor(p, 25, a)
}

func WirelessControllerAssocTime_Get(p *radius.Packet) (value time.Time) {
	value, _ = WirelessControllerAssocTime_Lookup(p)
	return
}

func WirelessControllerAssocTime_Gets(p *radius.Packet) (values []time.Time, err error) {
	var i time.Time
	for _, attr := range _Fortinet_GetsVendor(p, 25) {
		i, err = radius.Date(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func WirelessControllerAssocTime_Lookup(p *radius.Packet) (value time.Time, err error) {
	a, ok := _Fortinet_LookupVendor(p, 25)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value, err = radius.Date(a)
	return
}

func WirelessControllerAssocTime_Set(p *radius.Packet, value time.Time) (err error) {
	var a radius.Attribute
	a, err = radius.NewDate(value)
	if err != nil {
		return
	}
	return _Fortinet_SetVendor(p, 25, a)
}

func WirelessControllerAssocTime_Del(p *radius.Packet) {
	_Fortinet_DelVendor(p, 25)
}

func FortiWANAVPair_Add(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Fortinet_AddVendor(p, 26, a)
}

func FortiWANAVPair_AddString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Fortinet_AddVendor(p, 26, a)
}

func FortiWANAVPair_Get(p *radius.Packet) (value []byte) {
	value, _ = FortiWANAVPair_Lookup(p)
	return
}

func FortiWANAVPair_GetString(p *radius.Packet) (value string) {
	value, _ = FortiWANAVPair_LookupString(p)
	return
}

func FortiWANAVPair_Gets(p *radius.Packet) (values [][]byte, err error) {
	var i []byte
	for _, attr := range _Fortinet_GetsVendor(p, 26) {
		i = radius.Bytes(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func FortiWANAVPair_GetStrings(p *radius.Packet) (values []string, err error) {
	var i string
	for _, attr := range _Fortinet_GetsVendor(p, 26) {
		i = radius.String(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func FortiWANAVPair_Lookup(p *radius.Packet) (value []byte, err error) {
	a, ok := _Fortinet_LookupVendor(p, 26)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.Bytes(a)
	return
}

func FortiWANAVPair_LookupString(p *radius.Packet) (value string, err error) {
	a, ok := _Fortinet_LookupVendor(p, 26)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.String(a)
	return
}

func FortiWANAVPair_Set(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Fortinet_SetVendor(p, 26, a)
}

func FortiWANAVPair_SetString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Fortinet_SetVendor(p, 26, a)
}

func FortiWANAVPair_Del(p *radius.Packet) {
	_Fortinet_DelVendor(p, 26)
}

func FDDAccessProfile_Add(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Fortinet_AddVendor(p, 30, a)
}

func FDDAccessProfile_AddString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Fortinet_AddVendor(p, 30, a)
}

func FDDAccessProfile_Get(p *radius.Packet) (value []byte) {
	value, _ = FDDAccessProfile_Lookup(p)
	return
}

func FDDAccessProfile_GetString(p *radius.Packet) (value string) {
	value, _ = FDDAccessProfile_LookupString(p)
	return
}

func FDDAccessProfile_Gets(p *radius.Packet) (values [][]byte, err error) {
	var i []byte
	for _, attr := range _Fortinet_GetsVendor(p, 30) {
		i = radius.Bytes(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func FDDAccessProfile_GetStrings(p *radius.Packet) (values []string, err error) {
	var i string
	for _, attr := range _Fortinet_GetsVendor(p, 30) {
		i = radius.String(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func FDDAccessProfile_Lookup(p *radius.Packet) (value []byte, err error) {
	a, ok := _Fortinet_LookupVendor(p, 30)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.Bytes(a)
	return
}

func FDDAccessProfile_LookupString(p *radius.Packet) (value string, err error) {
	a, ok := _Fortinet_LookupVendor(p, 30)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.String(a)
	return
}

func FDDAccessProfile_Set(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Fortinet_SetVendor(p, 30, a)
}

func FDDAccessProfile_SetString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Fortinet_SetVendor(p, 30, a)
}

func FDDAccessProfile_Del(p *radius.Packet) {
	_Fortinet_DelVendor(p, 30)
}

func FDDTrustedHosts_Add(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Fortinet_AddVendor(p, 31, a)
}

func FDDTrustedHosts_AddString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Fortinet_AddVendor(p, 31, a)
}

func FDDTrustedHosts_Get(p *radius.Packet) (value []byte) {
	value, _ = FDDTrustedHosts_Lookup(p)
	return
}

func FDDTrustedHosts_GetString(p *radius.Packet) (value string) {
	value, _ = FDDTrustedHosts_LookupString(p)
	return
}

func FDDTrustedHosts_Gets(p *radius.Packet) (values [][]byte, err error) {
	var i []byte
	for _, attr := range _Fortinet_GetsVendor(p, 31) {
		i = radius.Bytes(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func FDDTrustedHosts_GetStrings(p *radius.Packet) (values []string, err error) {
	var i string
	for _, attr := range _Fortinet_GetsVendor(p, 31) {
		i = radius.String(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func FDDTrustedHosts_Lookup(p *radius.Packet) (value []byte, err error) {
	a, ok := _Fortinet_LookupVendor(p, 31)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.Bytes(a)
	return
}

func FDDTrustedHosts_LookupString(p *radius.Packet) (value string, err error) {
	a, ok := _Fortinet_LookupVendor(p, 31)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.String(a)
	return
}

func FDDTrustedHosts_Set(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Fortinet_SetVendor(p, 31, a)
}

func FDDTrustedHosts_SetString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Fortinet_SetVendor(p, 31, a)
}

func FDDTrustedHosts_Del(p *radius.Packet) {
	_Fortinet_DelVendor(p, 31)
}

func FDDSPPName_Add(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Fortinet_AddVendor(p, 32, a)
}

func FDDSPPName_AddString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Fortinet_AddVendor(p, 32, a)
}

func FDDSPPName_Get(p *radius.Packet) (value []byte) {
	value, _ = FDDSPPName_Lookup(p)
	return
}

func FDDSPPName_GetString(p *radius.Packet) (value string) {
	value, _ = FDDSPPName_LookupString(p)
	return
}

func FDDSPPName_Gets(p *radius.Packet) (values [][]byte, err error) {
	var i []byte
	for _, attr := range _Fortinet_GetsVendor(p, 32) {
		i = radius.Bytes(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func FDDSPPName_GetStrings(p *radius.Packet) (values []string, err error) {
	var i string
	for _, attr := range _Fortinet_GetsVendor(p, 32) {
		i = radius.String(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func FDDSPPName_Lookup(p *radius.Packet) (value []byte, err error) {
	a, ok := _Fortinet_LookupVendor(p, 32)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.Bytes(a)
	return
}

func FDDSPPName_LookupString(p *radius.Packet) (value string, err error) {
	a, ok := _Fortinet_LookupVendor(p, 32)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.String(a)
	return
}

func FDDSPPName_Set(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Fortinet_SetVendor(p, 32, a)
}

func FDDSPPName_SetString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Fortinet_SetVendor(p, 32, a)
}

func FDDSPPName_Del(p *radius.Packet) {
	_Fortinet_DelVendor(p, 32)
}

func FDDIsSystemAdmin_Add(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Fortinet_AddVendor(p, 33, a)
}

func FDDIsSystemAdmin_AddString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Fortinet_AddVendor(p, 33, a)
}

func FDDIsSystemAdmin_Get(p *radius.Packet) (value []byte) {
	value, _ = FDDIsSystemAdmin_Lookup(p)
	return
}

func FDDIsSystemAdmin_GetString(p *radius.Packet) (value string) {
	value, _ = FDDIsSystemAdmin_LookupString(p)
	return
}

func FDDIsSystemAdmin_Gets(p *radius.Packet) (values [][]byte, err error) {
	var i []byte
	for _, attr := range _Fortinet_GetsVendor(p, 33) {
		i = radius.Bytes(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func FDDIsSystemAdmin_GetStrings(p *radius.Packet) (values []string, err error) {
	var i string
	for _, attr := range _Fortinet_GetsVendor(p, 33) {
		i = radius.String(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func FDDIsSystemAdmin_Lookup(p *radius.Packet) (value []byte, err error) {
	a, ok := _Fortinet_LookupVendor(p, 33)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.Bytes(a)
	return
}

func FDDIsSystemAdmin_LookupString(p *radius.Packet) (value string, err error) {
	a, ok := _Fortinet_LookupVendor(p, 33)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.String(a)
	return
}

func FDDIsSystemAdmin_Set(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Fortinet_SetVendor(p, 33, a)
}

func FDDIsSystemAdmin_SetString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Fortinet_SetVendor(p, 33, a)
}

func FDDIsSystemAdmin_Del(p *radius.Packet) {
	_Fortinet_DelVendor(p, 33)
}

func FDDIsSPPAdmin_Add(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Fortinet_AddVendor(p, 34, a)
}

func FDDIsSPPAdmin_AddString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Fortinet_AddVendor(p, 34, a)
}

func FDDIsSPPAdmin_Get(p *radius.Packet) (value []byte) {
	value, _ = FDDIsSPPAdmin_Lookup(p)
	return
}

func FDDIsSPPAdmin_GetString(p *radius.Packet) (value string) {
	value, _ = FDDIsSPPAdmin_LookupString(p)
	return
}

func FDDIsSPPAdmin_Gets(p *radius.Packet) (values [][]byte, err error) {
	var i []byte
	for _, attr := range _Fortinet_GetsVendor(p, 34) {
		i = radius.Bytes(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func FDDIsSPPAdmin_GetStrings(p *radius.Packet) (values []string, err error) {
	var i string
	for _, attr := range _Fortinet_GetsVendor(p, 34) {
		i = radius.String(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func FDDIsSPPAdmin_Lookup(p *radius.Packet) (value []byte, err error) {
	a, ok := _Fortinet_LookupVendor(p, 34)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.Bytes(a)
	return
}

func FDDIsSPPAdmin_LookupString(p *radius.Packet) (value string, err error) {
	a, ok := _Fortinet_LookupVendor(p, 34)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.String(a)
	return
}

func FDDIsSPPAdmin_Set(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Fortinet_SetVendor(p, 34, a)
}

func FDDIsSPPAdmin_SetString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Fortinet_SetVendor(p, 34, a)
}

func FDDIsSPPAdmin_Del(p *radius.Packet) {
	_Fortinet_DelVendor(p, 34)
}

func FDDSPPPolicyGroup_Add(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Fortinet_AddVendor(p, 35, a)
}

func FDDSPPPolicyGroup_AddString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Fortinet_AddVendor(p, 35, a)
}

func FDDSPPPolicyGroup_Get(p *radius.Packet) (value []byte) {
	value, _ = FDDSPPPolicyGroup_Lookup(p)
	return
}

func FDDSPPPolicyGroup_GetString(p *radius.Packet) (value string) {
	value, _ = FDDSPPPolicyGroup_LookupString(p)
	return
}

func FDDSPPPolicyGroup_Gets(p *radius.Packet) (values [][]byte, err error) {
	var i []byte
	for _, attr := range _Fortinet_GetsVendor(p, 35) {
		i = radius.Bytes(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func FDDSPPPolicyGroup_GetStrings(p *radius.Packet) (values []string, err error) {
	var i string
	for _, attr := range _Fortinet_GetsVendor(p, 35) {
		i = radius.String(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func FDDSPPPolicyGroup_Lookup(p *radius.Packet) (value []byte, err error) {
	a, ok := _Fortinet_LookupVendor(p, 35)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.Bytes(a)
	return
}

func FDDSPPPolicyGroup_LookupString(p *radius.Packet) (value string, err error) {
	a, ok := _Fortinet_LookupVendor(p, 35)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.String(a)
	return
}

func FDDSPPPolicyGroup_Set(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Fortinet_SetVendor(p, 35, a)
}

func FDDSPPPolicyGroup_SetString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Fortinet_SetVendor(p, 35, a)
}

func FDDSPPPolicyGroup_Del(p *radius.Packet) {
	_Fortinet_DelVendor(p, 35)
}

func FDDAllowAPIAccess_Add(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Fortinet_AddVendor(p, 36, a)
}

func FDDAllowAPIAccess_AddString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Fortinet_AddVendor(p, 36, a)
}

func FDDAllowAPIAccess_Get(p *radius.Packet) (value []byte) {
	value, _ = FDDAllowAPIAccess_Lookup(p)
	return
}

func FDDAllowAPIAccess_GetString(p *radius.Packet) (value string) {
	value, _ = FDDAllowAPIAccess_LookupString(p)
	return
}

func FDDAllowAPIAccess_Gets(p *radius.Packet) (values [][]byte, err error) {
	var i []byte
	for _, attr := range _Fortinet_GetsVendor(p, 36) {
		i = radius.Bytes(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func FDDAllowAPIAccess_GetStrings(p *radius.Packet) (values []string, err error) {
	var i string
	for _, attr := range _Fortinet_GetsVendor(p, 36) {
		i = radius.String(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func FDDAllowAPIAccess_Lookup(p *radius.Packet) (value []byte, err error) {
	a, ok := _Fortinet_LookupVendor(p, 36)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.Bytes(a)
	return
}

func FDDAllowAPIAccess_LookupString(p *radius.Packet) (value string, err error) {
	a, ok := _Fortinet_LookupVendor(p, 36)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.String(a)
	return
}

func FDDAllowAPIAccess_Set(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Fortinet_SetVendor(p, 36, a)
}

func FDDAllowAPIAccess_SetString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Fortinet_SetVendor(p, 36, a)
}

func FDDAllowAPIAccess_Del(p *radius.Packet) {
	_Fortinet_DelVendor(p, 36)
}

func FpcUserRole_Add(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Fortinet_AddVendor(p, 40, a)
}

func FpcUserRole_AddString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Fortinet_AddVendor(p, 40, a)
}

func FpcUserRole_Get(p *radius.Packet) (value []byte) {
	value, _ = FpcUserRole_Lookup(p)
	return
}

func FpcUserRole_GetString(p *radius.Packet) (value string) {
	value, _ = FpcUserRole_LookupString(p)
	return
}

func FpcUserRole_Gets(p *radius.Packet) (values [][]byte, err error) {
	var i []byte
	for _, attr := range _Fortinet_GetsVendor(p, 40) {
		i = radius.Bytes(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func FpcUserRole_GetStrings(p *radius.Packet) (values []string, err error) {
	var i string
	for _, attr := range _Fortinet_GetsVendor(p, 40) {
		i = radius.String(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func FpcUserRole_Lookup(p *radius.Packet) (value []byte, err error) {
	a, ok := _Fortinet_LookupVendor(p, 40)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.Bytes(a)
	return
}

func FpcUserRole_LookupString(p *radius.Packet) (value string, err error) {
	a, ok := _Fortinet_LookupVendor(p, 40)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.String(a)
	return
}

func FpcUserRole_Set(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Fortinet_SetVendor(p, 40, a)
}

func FpcUserRole_SetString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Fortinet_SetVendor(p, 40, a)
}

func FpcUserRole_Del(p *radius.Packet) {
	_Fortinet_DelVendor(p, 40)
}

func TenantIdentification_Add(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Fortinet_AddVendor(p, 41, a)
}

func TenantIdentification_AddString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Fortinet_AddVendor(p, 41, a)
}

func TenantIdentification_Get(p *radius.Packet) (value []byte) {
	value, _ = TenantIdentification_Lookup(p)
	return
}

func TenantIdentification_GetString(p *radius.Packet) (value string) {
	value, _ = TenantIdentification_LookupString(p)
	return
}

func TenantIdentification_Gets(p *radius.Packet) (values [][]byte, err error) {
	var i []byte
	for _, attr := range _Fortinet_GetsVendor(p, 41) {
		i = radius.Bytes(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func TenantIdentification_GetStrings(p *radius.Packet) (values []string, err error) {
	var i string
	for _, attr := range _Fortinet_GetsVendor(p, 41) {
		i = radius.String(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func TenantIdentification_Lookup(p *radius.Packet) (value []byte, err error) {
	a, ok := _Fortinet_LookupVendor(p, 41)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.Bytes(a)
	return
}

func TenantIdentification_LookupString(p *radius.Packet) (value string, err error) {
	a, ok := _Fortinet_LookupVendor(p, 41)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.String(a)
	return
}

func TenantIdentification_Set(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Fortinet_SetVendor(p, 41, a)
}

func TenantIdentification_SetString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Fortinet_SetVendor(p, 41, a)
}

func TenantIdentification_Del(p *radius.Packet) {
	_Fortinet_DelVendor(p, 41)
}

func HostPortAVPair_Add(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Fortinet_AddVendor(p, 42, a)
}

func HostPortAVPair_AddString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Fortinet_AddVendor(p, 42, a)
}

func HostPortAVPair_Get(p *radius.Packet) (value []byte) {
	value, _ = HostPortAVPair_Lookup(p)
	return
}

func HostPortAVPair_GetString(p *radius.Packet) (value string) {
	value, _ = HostPortAVPair_LookupString(p)
	return
}

func HostPortAVPair_Gets(p *radius.Packet) (values [][]byte, err error) {
	var i []byte
	for _, attr := range _Fortinet_GetsVendor(p, 42) {
		i = radius.Bytes(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func HostPortAVPair_GetStrings(p *radius.Packet) (values []string, err error) {
	var i string
	for _, attr := range _Fortinet_GetsVendor(p, 42) {
		i = radius.String(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func HostPortAVPair_Lookup(p *radius.Packet) (value []byte, err error) {
	a, ok := _Fortinet_LookupVendor(p, 42)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.Bytes(a)
	return
}

func HostPortAVPair_LookupString(p *radius.Packet) (value string, err error) {
	a, ok := _Fortinet_LookupVendor(p, 42)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.String(a)
	return
}

func HostPortAVPair_Set(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Fortinet_SetVendor(p, 42, a)
}

func HostPortAVPair_SetString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Fortinet_SetVendor(p, 42, a)
}

func HostPortAVPair_Del(p *radius.Packet) {
	_Fortinet_DelVendor(p, 42)
}
