// Code generated by radius-dict-gen. DO NOT EDIT.

package hp

import (
	"strconv"

	"layeh.com/radius"
	"layeh.com/radius/rfc2865"
)

const (
	_HP_VendorID = 11
)

func _HP_AddVendor(p *radius.Packet, typ byte, attr radius.Attribute) (err error) {
	var vsa radius.Attribute
	vendor := make(radius.Attribute, 2+len(attr))
	vendor[0] = typ
	vendor[1] = byte(len(vendor))
	copy(vendor[2:], attr)
	vsa, err = radius.NewVendorSpecific(_HP_VendorID, vendor)
	if err != nil {
		return
	}
	p.Add(rfc2865.VendorSpecific_Type, vsa)
	return
}

func _HP_GetsVendor(p *radius.Packet, typ byte) (values []radius.Attribute) {
	for _, avp := range p.Attributes {
		if avp.Type != rfc2865.VendorSpecific_Type {
			continue
		}
		attr := avp.Attribute
		vendorID, vsa, err := radius.VendorSpecific(attr)
		if err != nil || vendorID != _HP_VendorID {
			continue
		}
		for len(vsa) >= 3 {
			vsaTyp, vsaLen := vsa[0], vsa[1]
			if int(vsaLen) > len(vsa) || vsaLen < 3 {
				break
			}
			if vsaTyp == typ {
				values = append(values, vsa[2:int(vsaLen)])
			}
			vsa = vsa[int(vsaLen):]
		}
	}
	return
}

func _HP_LookupVendor(p *radius.Packet, typ byte) (attr radius.Attribute, ok bool) {
	for _, avp := range p.Attributes {
		if avp.Type != rfc2865.VendorSpecific_Type {
			continue
		}
		attr := avp.Attribute
		vendorID, vsa, err := radius.VendorSpecific(attr)
		if err != nil || vendorID != _HP_VendorID {
			continue
		}
		for len(vsa) >= 3 {
			vsaTyp, vsaLen := vsa[0], vsa[1]
			if int(vsaLen) > len(vsa) || vsaLen < 3 {
				break
			}
			if vsaTyp == typ {
				return vsa[2:int(vsaLen)], true
			}
			vsa = vsa[int(vsaLen):]
		}
	}
	return
}

func _HP_SetVendor(p *radius.Packet, typ byte, attr radius.Attribute) (err error) {
	for i := 0; i < len(p.Attributes); {
		avp := p.Attributes[i]
		if avp.Type != rfc2865.VendorSpecific_Type {
			i++
			continue
		}
		vendorID, vsa, err := radius.VendorSpecific(avp.Attribute)
		if err != nil || vendorID != _HP_VendorID {
			i++
			continue
		}
		for j := 0; len(vsa[j:]) >= 3; {
			vsaTyp, vsaLen := vsa[0], vsa[1]
			if int(vsaLen) > len(vsa[j:]) || vsaLen < 3 {
				i++
				break
			}
			if vsaTyp == typ {
				vsa = append(vsa[:j], vsa[j+int(vsaLen):]...)
			}
			j += int(vsaLen)
		}
		if len(vsa) > 0 {
			copy(avp.Attribute[4:], vsa)
			i++
		} else {
			p.Attributes = append(p.Attributes[:i], p.Attributes[i+i:]...)
		}
	}
	return _HP_AddVendor(p, typ, attr)
}

func _HP_DelVendor(p *radius.Packet, typ byte) {
vsaLoop:
	for i := 0; i < len(p.Attributes); {
		avp := p.Attributes[i]
		if avp.Type != rfc2865.VendorSpecific_Type {
			i++
			continue
		}
		vendorID, vsa, err := radius.VendorSpecific(avp.Attribute)
		if err != nil || vendorID != _HP_VendorID {
			i++
			continue
		}
		offset := 0
		for len(vsa[offset:]) >= 3 {
			vsaTyp, vsaLen := vsa[offset], vsa[offset+1]
			if int(vsaLen) > len(vsa) || vsaLen < 3 {
				continue vsaLoop
			}
			if vsaTyp == typ {
				copy(vsa[offset:], vsa[offset+int(vsaLen):])
				vsa = vsa[:len(vsa)-int(vsaLen)]
			} else {
				offset += int(vsaLen)
			}
		}
		if offset == 0 {
			p.Attributes = append(p.Attributes[:i], p.Attributes[i+1:]...)
		} else {
			i++
		}
	}
	return
}

type PrivilegeLevel uint32

var PrivilegeLevel_Strings = map[PrivilegeLevel]string{}

func (a PrivilegeLevel) String() string {
	if str, ok := PrivilegeLevel_Strings[a]; ok {
		return str
	}
	return "PrivilegeLevel(" + strconv.FormatUint(uint64(a), 10) + ")"
}

func PrivilegeLevel_Add(p *radius.Packet, value PrivilegeLevel) (err error) {
	a := radius.NewInteger(uint32(value))
	return _HP_AddVendor(p, 1, a)
}

func PrivilegeLevel_Get(p *radius.Packet) (value PrivilegeLevel) {
	value, _ = PrivilegeLevel_Lookup(p)
	return
}

func PrivilegeLevel_Gets(p *radius.Packet) (values []PrivilegeLevel, err error) {
	var i uint32
	for _, attr := range _HP_GetsVendor(p, 1) {
		i, err = radius.Integer(attr)
		if err != nil {
			return
		}
		values = append(values, PrivilegeLevel(i))
	}
	return
}

func PrivilegeLevel_Lookup(p *radius.Packet) (value PrivilegeLevel, err error) {
	a, ok := _HP_LookupVendor(p, 1)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	var i uint32
	i, err = radius.Integer(a)
	if err != nil {
		return
	}
	value = PrivilegeLevel(i)
	return
}

func PrivilegeLevel_Set(p *radius.Packet, value PrivilegeLevel) (err error) {
	a := radius.NewInteger(uint32(value))
	return _HP_SetVendor(p, 1, a)
}

func PrivilegeLevel_Del(p *radius.Packet) {
	_HP_DelVendor(p, 1)
}

func CommandString_Add(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _HP_AddVendor(p, 2, a)
}

func CommandString_AddString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _HP_AddVendor(p, 2, a)
}

func CommandString_Get(p *radius.Packet) (value []byte) {
	value, _ = CommandString_Lookup(p)
	return
}

func CommandString_GetString(p *radius.Packet) (value string) {
	value, _ = CommandString_LookupString(p)
	return
}

func CommandString_Gets(p *radius.Packet) (values [][]byte, err error) {
	var i []byte
	for _, attr := range _HP_GetsVendor(p, 2) {
		i = radius.Bytes(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func CommandString_GetStrings(p *radius.Packet) (values []string, err error) {
	var i string
	for _, attr := range _HP_GetsVendor(p, 2) {
		i = radius.String(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func CommandString_Lookup(p *radius.Packet) (value []byte, err error) {
	a, ok := _HP_LookupVendor(p, 2)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.Bytes(a)
	return
}

func CommandString_LookupString(p *radius.Packet) (value string, err error) {
	a, ok := _HP_LookupVendor(p, 2)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.String(a)
	return
}

func CommandString_Set(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _HP_SetVendor(p, 2, a)
}

func CommandString_SetString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _HP_SetVendor(p, 2, a)
}

func CommandString_Del(p *radius.Packet) {
	_HP_DelVendor(p, 2)
}

type CommandException uint32

const (
	CommandException_Value_PermitList CommandException = 0
	CommandException_Value_DenyList   CommandException = 1
)

var CommandException_Strings = map[CommandException]string{
	CommandException_Value_PermitList: "Permit-List",
	CommandException_Value_DenyList:   "Deny-List",
}

func (a CommandException) String() string {
	if str, ok := CommandException_Strings[a]; ok {
		return str
	}
	return "CommandException(" + strconv.FormatUint(uint64(a), 10) + ")"
}

func CommandException_Add(p *radius.Packet, value CommandException) (err error) {
	a := radius.NewInteger(uint32(value))
	return _HP_AddVendor(p, 3, a)
}

func CommandException_Get(p *radius.Packet) (value CommandException) {
	value, _ = CommandException_Lookup(p)
	return
}

func CommandException_Gets(p *radius.Packet) (values []CommandException, err error) {
	var i uint32
	for _, attr := range _HP_GetsVendor(p, 3) {
		i, err = radius.Integer(attr)
		if err != nil {
			return
		}
		values = append(values, CommandException(i))
	}
	return
}

func CommandException_Lookup(p *radius.Packet) (value CommandException, err error) {
	a, ok := _HP_LookupVendor(p, 3)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	var i uint32
	i, err = radius.Integer(a)
	if err != nil {
		return
	}
	value = CommandException(i)
	return
}

func CommandException_Set(p *radius.Packet, value CommandException) (err error) {
	a := radius.NewInteger(uint32(value))
	return _HP_SetVendor(p, 3, a)
}

func CommandException_Del(p *radius.Packet) {
	_HP_DelVendor(p, 3)
}

type PortClientLimitDot1x uint32

var PortClientLimitDot1x_Strings = map[PortClientLimitDot1x]string{}

func (a PortClientLimitDot1x) String() string {
	if str, ok := PortClientLimitDot1x_Strings[a]; ok {
		return str
	}
	return "PortClientLimitDot1x(" + strconv.FormatUint(uint64(a), 10) + ")"
}

func PortClientLimitDot1x_Add(p *radius.Packet, value PortClientLimitDot1x) (err error) {
	a := radius.NewInteger(uint32(value))
	return _HP_AddVendor(p, 10, a)
}

func PortClientLimitDot1x_Get(p *radius.Packet) (value PortClientLimitDot1x) {
	value, _ = PortClientLimitDot1x_Lookup(p)
	return
}

func PortClientLimitDot1x_Gets(p *radius.Packet) (values []PortClientLimitDot1x, err error) {
	var i uint32
	for _, attr := range _HP_GetsVendor(p, 10) {
		i, err = radius.Integer(attr)
		if err != nil {
			return
		}
		values = append(values, PortClientLimitDot1x(i))
	}
	return
}

func PortClientLimitDot1x_Lookup(p *radius.Packet) (value PortClientLimitDot1x, err error) {
	a, ok := _HP_LookupVendor(p, 10)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	var i uint32
	i, err = radius.Integer(a)
	if err != nil {
		return
	}
	value = PortClientLimitDot1x(i)
	return
}

func PortClientLimitDot1x_Set(p *radius.Packet, value PortClientLimitDot1x) (err error) {
	a := radius.NewInteger(uint32(value))
	return _HP_SetVendor(p, 10, a)
}

func PortClientLimitDot1x_Del(p *radius.Packet) {
	_HP_DelVendor(p, 10)
}

type PortClientLimitMA uint32

var PortClientLimitMA_Strings = map[PortClientLimitMA]string{}

func (a PortClientLimitMA) String() string {
	if str, ok := PortClientLimitMA_Strings[a]; ok {
		return str
	}
	return "PortClientLimitMA(" + strconv.FormatUint(uint64(a), 10) + ")"
}

func PortClientLimitMA_Add(p *radius.Packet, value PortClientLimitMA) (err error) {
	a := radius.NewInteger(uint32(value))
	return _HP_AddVendor(p, 11, a)
}

func PortClientLimitMA_Get(p *radius.Packet) (value PortClientLimitMA) {
	value, _ = PortClientLimitMA_Lookup(p)
	return
}

func PortClientLimitMA_Gets(p *radius.Packet) (values []PortClientLimitMA, err error) {
	var i uint32
	for _, attr := range _HP_GetsVendor(p, 11) {
		i, err = radius.Integer(attr)
		if err != nil {
			return
		}
		values = append(values, PortClientLimitMA(i))
	}
	return
}

func PortClientLimitMA_Lookup(p *radius.Packet) (value PortClientLimitMA, err error) {
	a, ok := _HP_LookupVendor(p, 11)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	var i uint32
	i, err = radius.Integer(a)
	if err != nil {
		return
	}
	value = PortClientLimitMA(i)
	return
}

func PortClientLimitMA_Set(p *radius.Packet, value PortClientLimitMA) (err error) {
	a := radius.NewInteger(uint32(value))
	return _HP_SetVendor(p, 11, a)
}

func PortClientLimitMA_Del(p *radius.Packet) {
	_HP_DelVendor(p, 11)
}

type PortClientLimitWA uint32

var PortClientLimitWA_Strings = map[PortClientLimitWA]string{}

func (a PortClientLimitWA) String() string {
	if str, ok := PortClientLimitWA_Strings[a]; ok {
		return str
	}
	return "PortClientLimitWA(" + strconv.FormatUint(uint64(a), 10) + ")"
}

func PortClientLimitWA_Add(p *radius.Packet, value PortClientLimitWA) (err error) {
	a := radius.NewInteger(uint32(value))
	return _HP_AddVendor(p, 12, a)
}

func PortClientLimitWA_Get(p *radius.Packet) (value PortClientLimitWA) {
	value, _ = PortClientLimitWA_Lookup(p)
	return
}

func PortClientLimitWA_Gets(p *radius.Packet) (values []PortClientLimitWA, err error) {
	var i uint32
	for _, attr := range _HP_GetsVendor(p, 12) {
		i, err = radius.Integer(attr)
		if err != nil {
			return
		}
		values = append(values, PortClientLimitWA(i))
	}
	return
}

func PortClientLimitWA_Lookup(p *radius.Packet) (value PortClientLimitWA, err error) {
	a, ok := _HP_LookupVendor(p, 12)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	var i uint32
	i, err = radius.Integer(a)
	if err != nil {
		return
	}
	value = PortClientLimitWA(i)
	return
}

func PortClientLimitWA_Set(p *radius.Packet, value PortClientLimitWA) (err error) {
	a := radius.NewInteger(uint32(value))
	return _HP_SetVendor(p, 12, a)
}

func PortClientLimitWA_Del(p *radius.Packet) {
	_HP_DelVendor(p, 12)
}

type PortAuthModeDot1x uint32

const (
	PortAuthModeDot1x_Value_PortBased PortAuthModeDot1x = 1
	PortAuthModeDot1x_Value_UserBased PortAuthModeDot1x = 2
)

var PortAuthModeDot1x_Strings = map[PortAuthModeDot1x]string{
	PortAuthModeDot1x_Value_PortBased: "Port-Based",
	PortAuthModeDot1x_Value_UserBased: "User-Based",
}

func (a PortAuthModeDot1x) String() string {
	if str, ok := PortAuthModeDot1x_Strings[a]; ok {
		return str
	}
	return "PortAuthModeDot1x(" + strconv.FormatUint(uint64(a), 10) + ")"
}

func PortAuthModeDot1x_Add(p *radius.Packet, value PortAuthModeDot1x) (err error) {
	a := radius.NewInteger(uint32(value))
	return _HP_AddVendor(p, 13, a)
}

func PortAuthModeDot1x_Get(p *radius.Packet) (value PortAuthModeDot1x) {
	value, _ = PortAuthModeDot1x_Lookup(p)
	return
}

func PortAuthModeDot1x_Gets(p *radius.Packet) (values []PortAuthModeDot1x, err error) {
	var i uint32
	for _, attr := range _HP_GetsVendor(p, 13) {
		i, err = radius.Integer(attr)
		if err != nil {
			return
		}
		values = append(values, PortAuthModeDot1x(i))
	}
	return
}

func PortAuthModeDot1x_Lookup(p *radius.Packet) (value PortAuthModeDot1x, err error) {
	a, ok := _HP_LookupVendor(p, 13)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	var i uint32
	i, err = radius.Integer(a)
	if err != nil {
		return
	}
	value = PortAuthModeDot1x(i)
	return
}

func PortAuthModeDot1x_Set(p *radius.Packet, value PortAuthModeDot1x) (err error) {
	a := radius.NewInteger(uint32(value))
	return _HP_SetVendor(p, 13, a)
}

func PortAuthModeDot1x_Del(p *radius.Packet) {
	_HP_DelVendor(p, 13)
}

type PortMAPortMode uint32

const (
	PortMAPortMode_Value_UserBased PortMAPortMode = 0
	PortMAPortMode_Value_PortBased PortMAPortMode = 1
)

var PortMAPortMode_Strings = map[PortMAPortMode]string{
	PortMAPortMode_Value_UserBased: "User-Based",
	PortMAPortMode_Value_PortBased: "Port-Based",
}

func (a PortMAPortMode) String() string {
	if str, ok := PortMAPortMode_Strings[a]; ok {
		return str
	}
	return "PortMAPortMode(" + strconv.FormatUint(uint64(a), 10) + ")"
}

func PortMAPortMode_Add(p *radius.Packet, value PortMAPortMode) (err error) {
	a := radius.NewInteger(uint32(value))
	return _HP_AddVendor(p, 14, a)
}

func PortMAPortMode_Get(p *radius.Packet) (value PortMAPortMode) {
	value, _ = PortMAPortMode_Lookup(p)
	return
}

func PortMAPortMode_Gets(p *radius.Packet) (values []PortMAPortMode, err error) {
	var i uint32
	for _, attr := range _HP_GetsVendor(p, 14) {
		i, err = radius.Integer(attr)
		if err != nil {
			return
		}
		values = append(values, PortMAPortMode(i))
	}
	return
}

func PortMAPortMode_Lookup(p *radius.Packet) (value PortMAPortMode, err error) {
	a, ok := _HP_LookupVendor(p, 14)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	var i uint32
	i, err = radius.Integer(a)
	if err != nil {
		return
	}
	value = PortMAPortMode(i)
	return
}

func PortMAPortMode_Set(p *radius.Packet, value PortMAPortMode) (err error) {
	a := radius.NewInteger(uint32(value))
	return _HP_SetVendor(p, 14, a)
}

func PortMAPortMode_Del(p *radius.Packet) {
	_HP_DelVendor(p, 14)
}

type PortBounceHost uint32

var PortBounceHost_Strings = map[PortBounceHost]string{}

func (a PortBounceHost) String() string {
	if str, ok := PortBounceHost_Strings[a]; ok {
		return str
	}
	return "PortBounceHost(" + strconv.FormatUint(uint64(a), 10) + ")"
}

func PortBounceHost_Add(p *radius.Packet, value PortBounceHost) (err error) {
	a := radius.NewInteger(uint32(value))
	return _HP_AddVendor(p, 23, a)
}

func PortBounceHost_Get(p *radius.Packet) (value PortBounceHost) {
	value, _ = PortBounceHost_Lookup(p)
	return
}

func PortBounceHost_Gets(p *radius.Packet) (values []PortBounceHost, err error) {
	var i uint32
	for _, attr := range _HP_GetsVendor(p, 23) {
		i, err = radius.Integer(attr)
		if err != nil {
			return
		}
		values = append(values, PortBounceHost(i))
	}
	return
}

func PortBounceHost_Lookup(p *radius.Packet) (value PortBounceHost, err error) {
	a, ok := _HP_LookupVendor(p, 23)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	var i uint32
	i, err = radius.Integer(a)
	if err != nil {
		return
	}
	value = PortBounceHost(i)
	return
}

func PortBounceHost_Set(p *radius.Packet, value PortBounceHost) (err error) {
	a := radius.NewInteger(uint32(value))
	return _HP_SetVendor(p, 23, a)
}

func PortBounceHost_Del(p *radius.Packet) {
	_HP_DelVendor(p, 23)
}

func CaptivePortalURL_Add(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _HP_AddVendor(p, 24, a)
}

func CaptivePortalURL_AddString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _HP_AddVendor(p, 24, a)
}

func CaptivePortalURL_Get(p *radius.Packet) (value []byte) {
	value, _ = CaptivePortalURL_Lookup(p)
	return
}

func CaptivePortalURL_GetString(p *radius.Packet) (value string) {
	value, _ = CaptivePortalURL_LookupString(p)
	return
}

func CaptivePortalURL_Gets(p *radius.Packet) (values [][]byte, err error) {
	var i []byte
	for _, attr := range _HP_GetsVendor(p, 24) {
		i = radius.Bytes(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func CaptivePortalURL_GetStrings(p *radius.Packet) (values []string, err error) {
	var i string
	for _, attr := range _HP_GetsVendor(p, 24) {
		i = radius.String(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func CaptivePortalURL_Lookup(p *radius.Packet) (value []byte, err error) {
	a, ok := _HP_LookupVendor(p, 24)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.Bytes(a)
	return
}

func CaptivePortalURL_LookupString(p *radius.Packet) (value string, err error) {
	a, ok := _HP_LookupVendor(p, 24)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.String(a)
	return
}

func CaptivePortalURL_Set(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _HP_SetVendor(p, 24, a)
}

func CaptivePortalURL_SetString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _HP_SetVendor(p, 24, a)
}

func CaptivePortalURL_Del(p *radius.Packet) {
	_HP_DelVendor(p, 24)
}

func UserRole_Add(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _HP_AddVendor(p, 25, a)
}

func UserRole_AddString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _HP_AddVendor(p, 25, a)
}

func UserRole_Get(p *radius.Packet) (value []byte) {
	value, _ = UserRole_Lookup(p)
	return
}

func UserRole_GetString(p *radius.Packet) (value string) {
	value, _ = UserRole_LookupString(p)
	return
}

func UserRole_Gets(p *radius.Packet) (values [][]byte, err error) {
	var i []byte
	for _, attr := range _HP_GetsVendor(p, 25) {
		i = radius.Bytes(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func UserRole_GetStrings(p *radius.Packet) (values []string, err error) {
	var i string
	for _, attr := range _HP_GetsVendor(p, 25) {
		i = radius.String(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func UserRole_Lookup(p *radius.Packet) (value []byte, err error) {
	a, ok := _HP_LookupVendor(p, 25)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.Bytes(a)
	return
}

func UserRole_LookupString(p *radius.Packet) (value string, err error) {
	a, ok := _HP_LookupVendor(p, 25)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.String(a)
	return
}

func UserRole_Set(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _HP_SetVendor(p, 25, a)
}

func UserRole_SetString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _HP_SetVendor(p, 25, a)
}

func UserRole_Del(p *radius.Packet) {
	_HP_DelVendor(p, 25)
}

type ManagementProtocol uint32

const (
	ManagementProtocol_Value_HTTP  ManagementProtocol = 5
	ManagementProtocol_Value_HTTPS ManagementProtocol = 6
)

var ManagementProtocol_Strings = map[ManagementProtocol]string{
	ManagementProtocol_Value_HTTP:  "HTTP",
	ManagementProtocol_Value_HTTPS: "HTTPS",
}

func (a ManagementProtocol) String() string {
	if str, ok := ManagementProtocol_Strings[a]; ok {
		return str
	}
	return "ManagementProtocol(" + strconv.FormatUint(uint64(a), 10) + ")"
}

func ManagementProtocol_Add(p *radius.Packet, value ManagementProtocol) (err error) {
	a := radius.NewInteger(uint32(value))
	return _HP_AddVendor(p, 26, a)
}

func ManagementProtocol_Get(p *radius.Packet) (value ManagementProtocol) {
	value, _ = ManagementProtocol_Lookup(p)
	return
}

func ManagementProtocol_Gets(p *radius.Packet) (values []ManagementProtocol, err error) {
	var i uint32
	for _, attr := range _HP_GetsVendor(p, 26) {
		i, err = radius.Integer(attr)
		if err != nil {
			return
		}
		values = append(values, ManagementProtocol(i))
	}
	return
}

func ManagementProtocol_Lookup(p *radius.Packet) (value ManagementProtocol, err error) {
	a, ok := _HP_LookupVendor(p, 26)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	var i uint32
	i, err = radius.Integer(a)
	if err != nil {
		return
	}
	value = ManagementProtocol(i)
	return
}

func ManagementProtocol_Set(p *radius.Packet, value ManagementProtocol) (err error) {
	a := radius.NewInteger(uint32(value))
	return _HP_SetVendor(p, 26, a)
}

func ManagementProtocol_Del(p *radius.Packet) {
	_HP_DelVendor(p, 26)
}

func CPPMRole_Add(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _HP_AddVendor(p, 27, a)
}

func CPPMRole_AddString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _HP_AddVendor(p, 27, a)
}

func CPPMRole_Get(p *radius.Packet) (value []byte) {
	value, _ = CPPMRole_Lookup(p)
	return
}

func CPPMRole_GetString(p *radius.Packet) (value string) {
	value, _ = CPPMRole_LookupString(p)
	return
}

func CPPMRole_Gets(p *radius.Packet) (values [][]byte, err error) {
	var i []byte
	for _, attr := range _HP_GetsVendor(p, 27) {
		i = radius.Bytes(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func CPPMRole_GetStrings(p *radius.Packet) (values []string, err error) {
	var i string
	for _, attr := range _HP_GetsVendor(p, 27) {
		i = radius.String(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func CPPMRole_Lookup(p *radius.Packet) (value []byte, err error) {
	a, ok := _HP_LookupVendor(p, 27)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.Bytes(a)
	return
}

func CPPMRole_LookupString(p *radius.Packet) (value string, err error) {
	a, ok := _HP_LookupVendor(p, 27)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.String(a)
	return
}

func CPPMRole_Set(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _HP_SetVendor(p, 27, a)
}

func CPPMRole_SetString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _HP_SetVendor(p, 27, a)
}

func CPPMRole_Del(p *radius.Packet) {
	_HP_DelVendor(p, 27)
}

func CPPMSecondaryRole_Add(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _HP_AddVendor(p, 28, a)
}

func CPPMSecondaryRole_AddString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _HP_AddVendor(p, 28, a)
}

func CPPMSecondaryRole_Get(p *radius.Packet) (value []byte) {
	value, _ = CPPMSecondaryRole_Lookup(p)
	return
}

func CPPMSecondaryRole_GetString(p *radius.Packet) (value string) {
	value, _ = CPPMSecondaryRole_LookupString(p)
	return
}

func CPPMSecondaryRole_Gets(p *radius.Packet) (values [][]byte, err error) {
	var i []byte
	for _, attr := range _HP_GetsVendor(p, 28) {
		i = radius.Bytes(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func CPPMSecondaryRole_GetStrings(p *radius.Packet) (values []string, err error) {
	var i string
	for _, attr := range _HP_GetsVendor(p, 28) {
		i = radius.String(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func CPPMSecondaryRole_Lookup(p *radius.Packet) (value []byte, err error) {
	a, ok := _HP_LookupVendor(p, 28)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.Bytes(a)
	return
}

func CPPMSecondaryRole_LookupString(p *radius.Packet) (value string, err error) {
	a, ok := _HP_LookupVendor(p, 28)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.String(a)
	return
}

func CPPMSecondaryRole_Set(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _HP_SetVendor(p, 28, a)
}

func CPPMSecondaryRole_SetString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _HP_SetVendor(p, 28, a)
}

func CPPMSecondaryRole_Del(p *radius.Packet) {
	_HP_DelVendor(p, 28)
}

func PortPriorityRegenerationTable_Add(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _HP_AddVendor(p, 40, a)
}

func PortPriorityRegenerationTable_AddString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _HP_AddVendor(p, 40, a)
}

func PortPriorityRegenerationTable_Get(p *radius.Packet) (value []byte) {
	value, _ = PortPriorityRegenerationTable_Lookup(p)
	return
}

func PortPriorityRegenerationTable_GetString(p *radius.Packet) (value string) {
	value, _ = PortPriorityRegenerationTable_LookupString(p)
	return
}

func PortPriorityRegenerationTable_Gets(p *radius.Packet) (values [][]byte, err error) {
	var i []byte
	for _, attr := range _HP_GetsVendor(p, 40) {
		i = radius.Bytes(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func PortPriorityRegenerationTable_GetStrings(p *radius.Packet) (values []string, err error) {
	var i string
	for _, attr := range _HP_GetsVendor(p, 40) {
		i = radius.String(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func PortPriorityRegenerationTable_Lookup(p *radius.Packet) (value []byte, err error) {
	a, ok := _HP_LookupVendor(p, 40)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.Bytes(a)
	return
}

func PortPriorityRegenerationTable_LookupString(p *radius.Packet) (value string, err error) {
	a, ok := _HP_LookupVendor(p, 40)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.String(a)
	return
}

func PortPriorityRegenerationTable_Set(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _HP_SetVendor(p, 40, a)
}

func PortPriorityRegenerationTable_SetString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _HP_SetVendor(p, 40, a)
}

func PortPriorityRegenerationTable_Del(p *radius.Packet) {
	_HP_DelVendor(p, 40)
}

type BandwidthMaxIngress uint32

var BandwidthMaxIngress_Strings = map[BandwidthMaxIngress]string{}

func (a BandwidthMaxIngress) String() string {
	if str, ok := BandwidthMaxIngress_Strings[a]; ok {
		return str
	}
	return "BandwidthMaxIngress(" + strconv.FormatUint(uint64(a), 10) + ")"
}

func BandwidthMaxIngress_Add(p *radius.Packet, value BandwidthMaxIngress) (err error) {
	a := radius.NewInteger(uint32(value))
	return _HP_AddVendor(p, 46, a)
}

func BandwidthMaxIngress_Get(p *radius.Packet) (value BandwidthMaxIngress) {
	value, _ = BandwidthMaxIngress_Lookup(p)
	return
}

func BandwidthMaxIngress_Gets(p *radius.Packet) (values []BandwidthMaxIngress, err error) {
	var i uint32
	for _, attr := range _HP_GetsVendor(p, 46) {
		i, err = radius.Integer(attr)
		if err != nil {
			return
		}
		values = append(values, BandwidthMaxIngress(i))
	}
	return
}

func BandwidthMaxIngress_Lookup(p *radius.Packet) (value BandwidthMaxIngress, err error) {
	a, ok := _HP_LookupVendor(p, 46)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	var i uint32
	i, err = radius.Integer(a)
	if err != nil {
		return
	}
	value = BandwidthMaxIngress(i)
	return
}

func BandwidthMaxIngress_Set(p *radius.Packet, value BandwidthMaxIngress) (err error) {
	a := radius.NewInteger(uint32(value))
	return _HP_SetVendor(p, 46, a)
}

func BandwidthMaxIngress_Del(p *radius.Packet) {
	_HP_DelVendor(p, 46)
}

type BandwidthMaxEgress uint32

var BandwidthMaxEgress_Strings = map[BandwidthMaxEgress]string{}

func (a BandwidthMaxEgress) String() string {
	if str, ok := BandwidthMaxEgress_Strings[a]; ok {
		return str
	}
	return "BandwidthMaxEgress(" + strconv.FormatUint(uint64(a), 10) + ")"
}

func BandwidthMaxEgress_Add(p *radius.Packet, value BandwidthMaxEgress) (err error) {
	a := radius.NewInteger(uint32(value))
	return _HP_AddVendor(p, 48, a)
}

func BandwidthMaxEgress_Get(p *radius.Packet) (value BandwidthMaxEgress) {
	value, _ = BandwidthMaxEgress_Lookup(p)
	return
}

func BandwidthMaxEgress_Gets(p *radius.Packet) (values []BandwidthMaxEgress, err error) {
	var i uint32
	for _, attr := range _HP_GetsVendor(p, 48) {
		i, err = radius.Integer(attr)
		if err != nil {
			return
		}
		values = append(values, BandwidthMaxEgress(i))
	}
	return
}

func BandwidthMaxEgress_Lookup(p *radius.Packet) (value BandwidthMaxEgress, err error) {
	a, ok := _HP_LookupVendor(p, 48)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	var i uint32
	i, err = radius.Integer(a)
	if err != nil {
		return
	}
	value = BandwidthMaxEgress(i)
	return
}

func BandwidthMaxEgress_Set(p *radius.Packet, value BandwidthMaxEgress) (err error) {
	a := radius.NewInteger(uint32(value))
	return _HP_SetVendor(p, 48, a)
}

func BandwidthMaxEgress_Del(p *radius.Packet) {
	_HP_DelVendor(p, 48)
}

func IPFilterRaw_Add(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _HP_AddVendor(p, 61, a)
}

func IPFilterRaw_AddString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _HP_AddVendor(p, 61, a)
}

func IPFilterRaw_Get(p *radius.Packet) (value []byte) {
	value, _ = IPFilterRaw_Lookup(p)
	return
}

func IPFilterRaw_GetString(p *radius.Packet) (value string) {
	value, _ = IPFilterRaw_LookupString(p)
	return
}

func IPFilterRaw_Gets(p *radius.Packet) (values [][]byte, err error) {
	var i []byte
	for _, attr := range _HP_GetsVendor(p, 61) {
		i = radius.Bytes(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func IPFilterRaw_GetStrings(p *radius.Packet) (values []string, err error) {
	var i string
	for _, attr := range _HP_GetsVendor(p, 61) {
		i = radius.String(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func IPFilterRaw_Lookup(p *radius.Packet) (value []byte, err error) {
	a, ok := _HP_LookupVendor(p, 61)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.Bytes(a)
	return
}

func IPFilterRaw_LookupString(p *radius.Packet) (value string, err error) {
	a, ok := _HP_LookupVendor(p, 61)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.String(a)
	return
}

func IPFilterRaw_Set(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _HP_SetVendor(p, 61, a)
}

func IPFilterRaw_SetString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _HP_SetVendor(p, 61, a)
}

func IPFilterRaw_Del(p *radius.Packet) {
	_HP_DelVendor(p, 61)
}

func AccessProfile_Add(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _HP_AddVendor(p, 62, a)
}

func AccessProfile_AddString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _HP_AddVendor(p, 62, a)
}

func AccessProfile_Get(p *radius.Packet) (value []byte) {
	value, _ = AccessProfile_Lookup(p)
	return
}

func AccessProfile_GetString(p *radius.Packet) (value string) {
	value, _ = AccessProfile_LookupString(p)
	return
}

func AccessProfile_Gets(p *radius.Packet) (values [][]byte, err error) {
	var i []byte
	for _, attr := range _HP_GetsVendor(p, 62) {
		i = radius.Bytes(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func AccessProfile_GetStrings(p *radius.Packet) (values []string, err error) {
	var i string
	for _, attr := range _HP_GetsVendor(p, 62) {
		i = radius.String(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func AccessProfile_Lookup(p *radius.Packet) (value []byte, err error) {
	a, ok := _HP_LookupVendor(p, 62)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.Bytes(a)
	return
}

func AccessProfile_LookupString(p *radius.Packet) (value string, err error) {
	a, ok := _HP_LookupVendor(p, 62)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.String(a)
	return
}

func AccessProfile_Set(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _HP_SetVendor(p, 62, a)
}

func AccessProfile_SetString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _HP_SetVendor(p, 62, a)
}

func AccessProfile_Del(p *radius.Packet) {
	_HP_DelVendor(p, 62)
}

type NasRulesIPv6 uint32

var NasRulesIPv6_Strings = map[NasRulesIPv6]string{}

func (a NasRulesIPv6) String() string {
	if str, ok := NasRulesIPv6_Strings[a]; ok {
		return str
	}
	return "NasRulesIPv6(" + strconv.FormatUint(uint64(a), 10) + ")"
}

func NasRulesIPv6_Add(p *radius.Packet, value NasRulesIPv6) (err error) {
	a := radius.NewInteger(uint32(value))
	return _HP_AddVendor(p, 63, a)
}

func NasRulesIPv6_Get(p *radius.Packet) (value NasRulesIPv6) {
	value, _ = NasRulesIPv6_Lookup(p)
	return
}

func NasRulesIPv6_Gets(p *radius.Packet) (values []NasRulesIPv6, err error) {
	var i uint32
	for _, attr := range _HP_GetsVendor(p, 63) {
		i, err = radius.Integer(attr)
		if err != nil {
			return
		}
		values = append(values, NasRulesIPv6(i))
	}
	return
}

func NasRulesIPv6_Lookup(p *radius.Packet) (value NasRulesIPv6, err error) {
	a, ok := _HP_LookupVendor(p, 63)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	var i uint32
	i, err = radius.Integer(a)
	if err != nil {
		return
	}
	value = NasRulesIPv6(i)
	return
}

func NasRulesIPv6_Set(p *radius.Packet, value NasRulesIPv6) (err error) {
	a := radius.NewInteger(uint32(value))
	return _HP_SetVendor(p, 63, a)
}

func NasRulesIPv6_Del(p *radius.Packet) {
	_HP_DelVendor(p, 63)
}

type EgressVLANID uint32

var EgressVLANID_Strings = map[EgressVLANID]string{}

func (a EgressVLANID) String() string {
	if str, ok := EgressVLANID_Strings[a]; ok {
		return str
	}
	return "EgressVLANID(" + strconv.FormatUint(uint64(a), 10) + ")"
}

func EgressVLANID_Add(p *radius.Packet, value EgressVLANID) (err error) {
	a := radius.NewInteger(uint32(value))
	return _HP_AddVendor(p, 64, a)
}

func EgressVLANID_Get(p *radius.Packet) (value EgressVLANID) {
	value, _ = EgressVLANID_Lookup(p)
	return
}

func EgressVLANID_Gets(p *radius.Packet) (values []EgressVLANID, err error) {
	var i uint32
	for _, attr := range _HP_GetsVendor(p, 64) {
		i, err = radius.Integer(attr)
		if err != nil {
			return
		}
		values = append(values, EgressVLANID(i))
	}
	return
}

func EgressVLANID_Lookup(p *radius.Packet) (value EgressVLANID, err error) {
	a, ok := _HP_LookupVendor(p, 64)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	var i uint32
	i, err = radius.Integer(a)
	if err != nil {
		return
	}
	value = EgressVLANID(i)
	return
}

func EgressVLANID_Set(p *radius.Packet, value EgressVLANID) (err error) {
	a := radius.NewInteger(uint32(value))
	return _HP_SetVendor(p, 64, a)
}

func EgressVLANID_Del(p *radius.Packet) {
	_HP_DelVendor(p, 64)
}

func EgressVLANName_Add(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _HP_AddVendor(p, 65, a)
}

func EgressVLANName_AddString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _HP_AddVendor(p, 65, a)
}

func EgressVLANName_Get(p *radius.Packet) (value []byte) {
	value, _ = EgressVLANName_Lookup(p)
	return
}

func EgressVLANName_GetString(p *radius.Packet) (value string) {
	value, _ = EgressVLANName_LookupString(p)
	return
}

func EgressVLANName_Gets(p *radius.Packet) (values [][]byte, err error) {
	var i []byte
	for _, attr := range _HP_GetsVendor(p, 65) {
		i = radius.Bytes(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func EgressVLANName_GetStrings(p *radius.Packet) (values []string, err error) {
	var i string
	for _, attr := range _HP_GetsVendor(p, 65) {
		i = radius.String(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func EgressVLANName_Lookup(p *radius.Packet) (value []byte, err error) {
	a, ok := _HP_LookupVendor(p, 65)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.Bytes(a)
	return
}

func EgressVLANName_LookupString(p *radius.Packet) (value string, err error) {
	a, ok := _HP_LookupVendor(p, 65)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.String(a)
	return
}

func EgressVLANName_Set(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _HP_SetVendor(p, 65, a)
}

func EgressVLANName_SetString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _HP_SetVendor(p, 65, a)
}

func EgressVLANName_Del(p *radius.Packet) {
	_HP_DelVendor(p, 65)
}

func BonjourInboundProfile_Add(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _HP_AddVendor(p, 66, a)
}

func BonjourInboundProfile_AddString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _HP_AddVendor(p, 66, a)
}

func BonjourInboundProfile_Get(p *radius.Packet) (value []byte) {
	value, _ = BonjourInboundProfile_Lookup(p)
	return
}

func BonjourInboundProfile_GetString(p *radius.Packet) (value string) {
	value, _ = BonjourInboundProfile_LookupString(p)
	return
}

func BonjourInboundProfile_Gets(p *radius.Packet) (values [][]byte, err error) {
	var i []byte
	for _, attr := range _HP_GetsVendor(p, 66) {
		i = radius.Bytes(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func BonjourInboundProfile_GetStrings(p *radius.Packet) (values []string, err error) {
	var i string
	for _, attr := range _HP_GetsVendor(p, 66) {
		i = radius.String(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func BonjourInboundProfile_Lookup(p *radius.Packet) (value []byte, err error) {
	a, ok := _HP_LookupVendor(p, 66)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.Bytes(a)
	return
}

func BonjourInboundProfile_LookupString(p *radius.Packet) (value string, err error) {
	a, ok := _HP_LookupVendor(p, 66)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.String(a)
	return
}

func BonjourInboundProfile_Set(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _HP_SetVendor(p, 66, a)
}

func BonjourInboundProfile_SetString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _HP_SetVendor(p, 66, a)
}

func BonjourInboundProfile_Del(p *radius.Packet) {
	_HP_DelVendor(p, 66)
}

func BonjourOutboundProfile_Add(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _HP_AddVendor(p, 67, a)
}

func BonjourOutboundProfile_AddString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _HP_AddVendor(p, 67, a)
}

func BonjourOutboundProfile_Get(p *radius.Packet) (value []byte) {
	value, _ = BonjourOutboundProfile_Lookup(p)
	return
}

func BonjourOutboundProfile_GetString(p *radius.Packet) (value string) {
	value, _ = BonjourOutboundProfile_LookupString(p)
	return
}

func BonjourOutboundProfile_Gets(p *radius.Packet) (values [][]byte, err error) {
	var i []byte
	for _, attr := range _HP_GetsVendor(p, 67) {
		i = radius.Bytes(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func BonjourOutboundProfile_GetStrings(p *radius.Packet) (values []string, err error) {
	var i string
	for _, attr := range _HP_GetsVendor(p, 67) {
		i = radius.String(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func BonjourOutboundProfile_Lookup(p *radius.Packet) (value []byte, err error) {
	a, ok := _HP_LookupVendor(p, 67)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.Bytes(a)
	return
}

func BonjourOutboundProfile_LookupString(p *radius.Packet) (value string, err error) {
	a, ok := _HP_LookupVendor(p, 67)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.String(a)
	return
}

func BonjourOutboundProfile_Set(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _HP_SetVendor(p, 67, a)
}

func BonjourOutboundProfile_SetString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _HP_SetVendor(p, 67, a)
}

func BonjourOutboundProfile_Del(p *radius.Packet) {
	_HP_DelVendor(p, 67)
}

func URIString_Add(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _HP_AddVendor(p, 80, a)
}

func URIString_AddString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _HP_AddVendor(p, 80, a)
}

func URIString_Get(p *radius.Packet) (value []byte) {
	value, _ = URIString_Lookup(p)
	return
}

func URIString_GetString(p *radius.Packet) (value string) {
	value, _ = URIString_LookupString(p)
	return
}

func URIString_Gets(p *radius.Packet) (values [][]byte, err error) {
	var i []byte
	for _, attr := range _HP_GetsVendor(p, 80) {
		i = radius.Bytes(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func URIString_GetStrings(p *radius.Packet) (values []string, err error) {
	var i string
	for _, attr := range _HP_GetsVendor(p, 80) {
		i = radius.String(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func URIString_Lookup(p *radius.Packet) (value []byte, err error) {
	a, ok := _HP_LookupVendor(p, 80)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.Bytes(a)
	return
}

func URIString_LookupString(p *radius.Packet) (value string, err error) {
	a, ok := _HP_LookupVendor(p, 80)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.String(a)
	return
}

func URIString_Set(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _HP_SetVendor(p, 80, a)
}

func URIString_SetString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _HP_SetVendor(p, 80, a)
}

func URIString_Del(p *radius.Packet) {
	_HP_DelVendor(p, 80)
}

func URIJSONString_Add(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _HP_AddVendor(p, 81, a)
}

func URIJSONString_AddString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _HP_AddVendor(p, 81, a)
}

func URIJSONString_Get(p *radius.Packet) (value []byte) {
	value, _ = URIJSONString_Lookup(p)
	return
}

func URIJSONString_GetString(p *radius.Packet) (value string) {
	value, _ = URIJSONString_LookupString(p)
	return
}

func URIJSONString_Gets(p *radius.Packet) (values [][]byte, err error) {
	var i []byte
	for _, attr := range _HP_GetsVendor(p, 81) {
		i = radius.Bytes(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func URIJSONString_GetStrings(p *radius.Packet) (values []string, err error) {
	var i string
	for _, attr := range _HP_GetsVendor(p, 81) {
		i = radius.String(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func URIJSONString_Lookup(p *radius.Packet) (value []byte, err error) {
	a, ok := _HP_LookupVendor(p, 81)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.Bytes(a)
	return
}

func URIJSONString_LookupString(p *radius.Packet) (value string, err error) {
	a, ok := _HP_LookupVendor(p, 81)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.String(a)
	return
}

func URIJSONString_Set(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _HP_SetVendor(p, 81, a)
}

func URIJSONString_SetString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _HP_SetVendor(p, 81, a)
}

func URIJSONString_Del(p *radius.Packet) {
	_HP_DelVendor(p, 81)
}

func URIAccess_Add(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _HP_AddVendor(p, 82, a)
}

func URIAccess_AddString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _HP_AddVendor(p, 82, a)
}

func URIAccess_Get(p *radius.Packet) (value []byte) {
	value, _ = URIAccess_Lookup(p)
	return
}

func URIAccess_GetString(p *radius.Packet) (value string) {
	value, _ = URIAccess_LookupString(p)
	return
}

func URIAccess_Gets(p *radius.Packet) (values [][]byte, err error) {
	var i []byte
	for _, attr := range _HP_GetsVendor(p, 82) {
		i = radius.Bytes(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func URIAccess_GetStrings(p *radius.Packet) (values []string, err error) {
	var i string
	for _, attr := range _HP_GetsVendor(p, 82) {
		i = radius.String(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func URIAccess_Lookup(p *radius.Packet) (value []byte, err error) {
	a, ok := _HP_LookupVendor(p, 82)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.Bytes(a)
	return
}

func URIAccess_LookupString(p *radius.Packet) (value string, err error) {
	a, ok := _HP_LookupVendor(p, 82)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.String(a)
	return
}

func URIAccess_Set(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _HP_SetVendor(p, 82, a)
}

func URIAccess_SetString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _HP_SetVendor(p, 82, a)
}

func URIAccess_Del(p *radius.Packet) {
	_HP_DelVendor(p, 82)
}

type URIException uint32

var URIException_Strings = map[URIException]string{}

func (a URIException) String() string {
	if str, ok := URIException_Strings[a]; ok {
		return str
	}
	return "URIException(" + strconv.FormatUint(uint64(a), 10) + ")"
}

func URIException_Add(p *radius.Packet, value URIException) (err error) {
	a := radius.NewInteger(uint32(value))
	return _HP_AddVendor(p, 83, a)
}

func URIException_Get(p *radius.Packet) (value URIException) {
	value, _ = URIException_Lookup(p)
	return
}

func URIException_Gets(p *radius.Packet) (values []URIException, err error) {
	var i uint32
	for _, attr := range _HP_GetsVendor(p, 83) {
		i, err = radius.Integer(attr)
		if err != nil {
			return
		}
		values = append(values, URIException(i))
	}
	return
}

func URIException_Lookup(p *radius.Packet) (value URIException, err error) {
	a, ok := _HP_LookupVendor(p, 83)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	var i uint32
	i, err = radius.Integer(a)
	if err != nil {
		return
	}
	value = URIException(i)
	return
}

func URIException_Set(p *radius.Packet, value URIException) (err error) {
	a := radius.NewInteger(uint32(value))
	return _HP_SetVendor(p, 83, a)
}

func URIException_Del(p *radius.Packet) {
	_HP_DelVendor(p, 83)
}

func VCGroups_Add(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _HP_AddVendor(p, 192, a)
}

func VCGroups_AddString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _HP_AddVendor(p, 192, a)
}

func VCGroups_Get(p *radius.Packet) (value []byte) {
	value, _ = VCGroups_Lookup(p)
	return
}

func VCGroups_GetString(p *radius.Packet) (value string) {
	value, _ = VCGroups_LookupString(p)
	return
}

func VCGroups_Gets(p *radius.Packet) (values [][]byte, err error) {
	var i []byte
	for _, attr := range _HP_GetsVendor(p, 192) {
		i = radius.Bytes(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func VCGroups_GetStrings(p *radius.Packet) (values []string, err error) {
	var i string
	for _, attr := range _HP_GetsVendor(p, 192) {
		i = radius.String(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func VCGroups_Lookup(p *radius.Packet) (value []byte, err error) {
	a, ok := _HP_LookupVendor(p, 192)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.Bytes(a)
	return
}

func VCGroups_LookupString(p *radius.Packet) (value string, err error) {
	a, ok := _HP_LookupVendor(p, 192)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.String(a)
	return
}

func VCGroups_Set(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _HP_SetVendor(p, 192, a)
}

func VCGroups_SetString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _HP_SetVendor(p, 192, a)
}

func VCGroups_Del(p *radius.Packet) {
	_HP_DelVendor(p, 192)
}

func CapabilityAdvert_Add(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _HP_AddVendor(p, 255, a)
}

func CapabilityAdvert_AddString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _HP_AddVendor(p, 255, a)
}

func CapabilityAdvert_Get(p *radius.Packet) (value []byte) {
	value, _ = CapabilityAdvert_Lookup(p)
	return
}

func CapabilityAdvert_GetString(p *radius.Packet) (value string) {
	value, _ = CapabilityAdvert_LookupString(p)
	return
}

func CapabilityAdvert_Gets(p *radius.Packet) (values [][]byte, err error) {
	var i []byte
	for _, attr := range _HP_GetsVendor(p, 255) {
		i = radius.Bytes(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func CapabilityAdvert_GetStrings(p *radius.Packet) (values []string, err error) {
	var i string
	for _, attr := range _HP_GetsVendor(p, 255) {
		i = radius.String(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func CapabilityAdvert_Lookup(p *radius.Packet) (value []byte, err error) {
	a, ok := _HP_LookupVendor(p, 255)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.Bytes(a)
	return
}

func CapabilityAdvert_LookupString(p *radius.Packet) (value string, err error) {
	a, ok := _HP_LookupVendor(p, 255)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.String(a)
	return
}

func CapabilityAdvert_Set(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _HP_SetVendor(p, 255, a)
}

func CapabilityAdvert_SetString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _HP_SetVendor(p, 255, a)
}

func CapabilityAdvert_Del(p *radius.Packet) {
	_HP_DelVendor(p, 255)
}
