// Code generated by radius-dict-gen. DO NOT EDIT.

package alcatel

import (
	"net"
	"strconv"

	"layeh.com/radius"
	"layeh.com/radius/rfc2865"
)

const (
	_Alcatel_VendorID = 3041
)

func _Alcatel_AddVendor(p *radius.Packet, typ byte, attr radius.Attribute) (err error) {
	var vsa radius.Attribute
	vendor := make(radius.Attribute, 2+len(attr))
	vendor[0] = typ
	vendor[1] = byte(len(vendor))
	copy(vendor[2:], attr)
	vsa, err = radius.NewVendorSpecific(_Alcatel_VendorID, vendor)
	if err != nil {
		return
	}
	p.Add(rfc2865.VendorSpecific_Type, vsa)
	return
}

func _Alcatel_GetsVendor(p *radius.Packet, typ byte) (values []radius.Attribute) {
	for _, avp := range p.Attributes {
		if avp.Type != rfc2865.VendorSpecific_Type {
			continue
		}
		attr := avp.Attribute
		vendorID, vsa, err := radius.VendorSpecific(attr)
		if err != nil || vendorID != _Alcatel_VendorID {
			continue
		}
		for len(vsa) >= 3 {
			vsaTyp, vsaLen := vsa[0], vsa[1]
			if int(vsaLen) > len(vsa) || vsaLen < 3 {
				break
			}
			if vsaTyp == typ {
				values = append(values, vsa[2:int(vsaLen)])
			}
			vsa = vsa[int(vsaLen):]
		}
	}
	return
}

func _Alcatel_LookupVendor(p *radius.Packet, typ byte) (attr radius.Attribute, ok bool) {
	for _, avp := range p.Attributes {
		if avp.Type != rfc2865.VendorSpecific_Type {
			continue
		}
		attr := avp.Attribute
		vendorID, vsa, err := radius.VendorSpecific(attr)
		if err != nil || vendorID != _Alcatel_VendorID {
			continue
		}
		for len(vsa) >= 3 {
			vsaTyp, vsaLen := vsa[0], vsa[1]
			if int(vsaLen) > len(vsa) || vsaLen < 3 {
				break
			}
			if vsaTyp == typ {
				return vsa[2:int(vsaLen)], true
			}
			vsa = vsa[int(vsaLen):]
		}
	}
	return
}

func _Alcatel_SetVendor(p *radius.Packet, typ byte, attr radius.Attribute) (err error) {
	for i := 0; i < len(p.Attributes); {
		avp := p.Attributes[i]
		if avp.Type != rfc2865.VendorSpecific_Type {
			i++
			continue
		}
		vendorID, vsa, err := radius.VendorSpecific(avp.Attribute)
		if err != nil || vendorID != _Alcatel_VendorID {
			i++
			continue
		}
		for j := 0; len(vsa[j:]) >= 3; {
			vsaTyp, vsaLen := vsa[0], vsa[1]
			if int(vsaLen) > len(vsa[j:]) || vsaLen < 3 {
				i++
				break
			}
			if vsaTyp == typ {
				vsa = append(vsa[:j], vsa[j+int(vsaLen):]...)
			}
			j += int(vsaLen)
		}
		if len(vsa) > 0 {
			copy(avp.Attribute[4:], vsa)
			i++
		} else {
			p.Attributes = append(p.Attributes[:i], p.Attributes[i+i:]...)
		}
	}
	return _Alcatel_AddVendor(p, typ, attr)
}

func _Alcatel_DelVendor(p *radius.Packet, typ byte) {
vsaLoop:
	for i := 0; i < len(p.Attributes); {
		avp := p.Attributes[i]
		if avp.Type != rfc2865.VendorSpecific_Type {
			i++
			continue
		}
		vendorID, vsa, err := radius.VendorSpecific(avp.Attribute)
		if err != nil || vendorID != _Alcatel_VendorID {
			i++
			continue
		}
		offset := 0
		for len(vsa[offset:]) >= 3 {
			vsaTyp, vsaLen := vsa[offset], vsa[offset+1]
			if int(vsaLen) > len(vsa) || vsaLen < 3 {
				continue vsaLoop
			}
			if vsaTyp == typ {
				copy(vsa[offset:], vsa[offset+int(vsaLen):])
				vsa = vsa[:len(vsa)-int(vsaLen)]
			} else {
				offset += int(vsaLen)
			}
		}
		if offset == 0 {
			p.Attributes = append(p.Attributes[:i], p.Attributes[i+1:]...)
		} else {
			i++
		}
	}
	return
}

func ClientPrimaryDNS_Add(p *radius.Packet, value net.IP) (err error) {
	var a radius.Attribute
	a, err = radius.NewIPAddr(value)
	if err != nil {
		return
	}
	return _Alcatel_AddVendor(p, 5, a)
}

func ClientPrimaryDNS_Get(p *radius.Packet) (value net.IP) {
	value, _ = ClientPrimaryDNS_Lookup(p)
	return
}

func ClientPrimaryDNS_Gets(p *radius.Packet) (values []net.IP, err error) {
	var i net.IP
	for _, attr := range _Alcatel_GetsVendor(p, 5) {
		i, err = radius.IPAddr(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func ClientPrimaryDNS_Lookup(p *radius.Packet) (value net.IP, err error) {
	a, ok := _Alcatel_LookupVendor(p, 5)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value, err = radius.IPAddr(a)
	return
}

func ClientPrimaryDNS_Set(p *radius.Packet, value net.IP) (err error) {
	var a radius.Attribute
	a, err = radius.NewIPAddr(value)
	if err != nil {
		return
	}
	return _Alcatel_SetVendor(p, 5, a)
}

func ClientPrimaryDNS_Del(p *radius.Packet) {
	_Alcatel_DelVendor(p, 5)
}

func ClientPrimaryWINSNBNS_Add(p *radius.Packet, value net.IP) (err error) {
	var a radius.Attribute
	a, err = radius.NewIPAddr(value)
	if err != nil {
		return
	}
	return _Alcatel_AddVendor(p, 6, a)
}

func ClientPrimaryWINSNBNS_Get(p *radius.Packet) (value net.IP) {
	value, _ = ClientPrimaryWINSNBNS_Lookup(p)
	return
}

func ClientPrimaryWINSNBNS_Gets(p *radius.Packet) (values []net.IP, err error) {
	var i net.IP
	for _, attr := range _Alcatel_GetsVendor(p, 6) {
		i, err = radius.IPAddr(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func ClientPrimaryWINSNBNS_Lookup(p *radius.Packet) (value net.IP, err error) {
	a, ok := _Alcatel_LookupVendor(p, 6)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value, err = radius.IPAddr(a)
	return
}

func ClientPrimaryWINSNBNS_Set(p *radius.Packet, value net.IP) (err error) {
	var a radius.Attribute
	a, err = radius.NewIPAddr(value)
	if err != nil {
		return
	}
	return _Alcatel_SetVendor(p, 6, a)
}

func ClientPrimaryWINSNBNS_Del(p *radius.Packet) {
	_Alcatel_DelVendor(p, 6)
}

func ClientSecondaryWINSNBNS_Add(p *radius.Packet, value net.IP) (err error) {
	var a radius.Attribute
	a, err = radius.NewIPAddr(value)
	if err != nil {
		return
	}
	return _Alcatel_AddVendor(p, 7, a)
}

func ClientSecondaryWINSNBNS_Get(p *radius.Packet) (value net.IP) {
	value, _ = ClientSecondaryWINSNBNS_Lookup(p)
	return
}

func ClientSecondaryWINSNBNS_Gets(p *radius.Packet) (values []net.IP, err error) {
	var i net.IP
	for _, attr := range _Alcatel_GetsVendor(p, 7) {
		i, err = radius.IPAddr(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func ClientSecondaryWINSNBNS_Lookup(p *radius.Packet) (value net.IP, err error) {
	a, ok := _Alcatel_LookupVendor(p, 7)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value, err = radius.IPAddr(a)
	return
}

func ClientSecondaryWINSNBNS_Set(p *radius.Packet, value net.IP) (err error) {
	var a radius.Attribute
	a, err = radius.NewIPAddr(value)
	if err != nil {
		return
	}
	return _Alcatel_SetVendor(p, 7, a)
}

func ClientSecondaryWINSNBNS_Del(p *radius.Packet) {
	_Alcatel_DelVendor(p, 7)
}

func ClientSecondaryDNS_Add(p *radius.Packet, value net.IP) (err error) {
	var a radius.Attribute
	a, err = radius.NewIPAddr(value)
	if err != nil {
		return
	}
	return _Alcatel_AddVendor(p, 8, a)
}

func ClientSecondaryDNS_Get(p *radius.Packet) (value net.IP) {
	value, _ = ClientSecondaryDNS_Lookup(p)
	return
}

func ClientSecondaryDNS_Gets(p *radius.Packet) (values []net.IP, err error) {
	var i net.IP
	for _, attr := range _Alcatel_GetsVendor(p, 8) {
		i, err = radius.IPAddr(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func ClientSecondaryDNS_Lookup(p *radius.Packet) (value net.IP, err error) {
	a, ok := _Alcatel_LookupVendor(p, 8)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value, err = radius.IPAddr(a)
	return
}

func ClientSecondaryDNS_Set(p *radius.Packet, value net.IP) (err error) {
	var a radius.Attribute
	a, err = radius.NewIPAddr(value)
	if err != nil {
		return
	}
	return _Alcatel_SetVendor(p, 8, a)
}

func ClientSecondaryDNS_Del(p *radius.Packet) {
	_Alcatel_DelVendor(p, 8)
}

func PPPAddress_Add(p *radius.Packet, value net.IP) (err error) {
	var a radius.Attribute
	a, err = radius.NewIPAddr(value)
	if err != nil {
		return
	}
	return _Alcatel_AddVendor(p, 9, a)
}

func PPPAddress_Get(p *radius.Packet) (value net.IP) {
	value, _ = PPPAddress_Lookup(p)
	return
}

func PPPAddress_Gets(p *radius.Packet) (values []net.IP, err error) {
	var i net.IP
	for _, attr := range _Alcatel_GetsVendor(p, 9) {
		i, err = radius.IPAddr(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func PPPAddress_Lookup(p *radius.Packet) (value net.IP, err error) {
	a, ok := _Alcatel_LookupVendor(p, 9)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value, err = radius.IPAddr(a)
	return
}

func PPPAddress_Set(p *radius.Packet, value net.IP) (err error) {
	var a radius.Attribute
	a, err = radius.NewIPAddr(value)
	if err != nil {
		return
	}
	return _Alcatel_SetVendor(p, 9, a)
}

func PPPAddress_Del(p *radius.Packet) {
	_Alcatel_DelVendor(p, 9)
}

func PPPNetmask_Add(p *radius.Packet, value net.IP) (err error) {
	var a radius.Attribute
	a, err = radius.NewIPAddr(value)
	if err != nil {
		return
	}
	return _Alcatel_AddVendor(p, 10, a)
}

func PPPNetmask_Get(p *radius.Packet) (value net.IP) {
	value, _ = PPPNetmask_Lookup(p)
	return
}

func PPPNetmask_Gets(p *radius.Packet) (values []net.IP, err error) {
	var i net.IP
	for _, attr := range _Alcatel_GetsVendor(p, 10) {
		i, err = radius.IPAddr(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func PPPNetmask_Lookup(p *radius.Packet) (value net.IP, err error) {
	a, ok := _Alcatel_LookupVendor(p, 10)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value, err = radius.IPAddr(a)
	return
}

func PPPNetmask_Set(p *radius.Packet, value net.IP) (err error) {
	var a radius.Attribute
	a, err = radius.NewIPAddr(value)
	if err != nil {
		return
	}
	return _Alcatel_SetVendor(p, 10, a)
}

func PPPNetmask_Del(p *radius.Packet) {
	_Alcatel_DelVendor(p, 10)
}

func PrimaryHomeAgent_Add(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Alcatel_AddVendor(p, 12, a)
}

func PrimaryHomeAgent_AddString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Alcatel_AddVendor(p, 12, a)
}

func PrimaryHomeAgent_Get(p *radius.Packet) (value []byte) {
	value, _ = PrimaryHomeAgent_Lookup(p)
	return
}

func PrimaryHomeAgent_GetString(p *radius.Packet) (value string) {
	value, _ = PrimaryHomeAgent_LookupString(p)
	return
}

func PrimaryHomeAgent_Gets(p *radius.Packet) (values [][]byte, err error) {
	var i []byte
	for _, attr := range _Alcatel_GetsVendor(p, 12) {
		i = radius.Bytes(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func PrimaryHomeAgent_GetStrings(p *radius.Packet) (values []string, err error) {
	var i string
	for _, attr := range _Alcatel_GetsVendor(p, 12) {
		i = radius.String(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func PrimaryHomeAgent_Lookup(p *radius.Packet) (value []byte, err error) {
	a, ok := _Alcatel_LookupVendor(p, 12)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.Bytes(a)
	return
}

func PrimaryHomeAgent_LookupString(p *radius.Packet) (value string, err error) {
	a, ok := _Alcatel_LookupVendor(p, 12)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.String(a)
	return
}

func PrimaryHomeAgent_Set(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Alcatel_SetVendor(p, 12, a)
}

func PrimaryHomeAgent_SetString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Alcatel_SetVendor(p, 12, a)
}

func PrimaryHomeAgent_Del(p *radius.Packet) {
	_Alcatel_DelVendor(p, 12)
}

func SecondaryHomeAgent_Add(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Alcatel_AddVendor(p, 13, a)
}

func SecondaryHomeAgent_AddString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Alcatel_AddVendor(p, 13, a)
}

func SecondaryHomeAgent_Get(p *radius.Packet) (value []byte) {
	value, _ = SecondaryHomeAgent_Lookup(p)
	return
}

func SecondaryHomeAgent_GetString(p *radius.Packet) (value string) {
	value, _ = SecondaryHomeAgent_LookupString(p)
	return
}

func SecondaryHomeAgent_Gets(p *radius.Packet) (values [][]byte, err error) {
	var i []byte
	for _, attr := range _Alcatel_GetsVendor(p, 13) {
		i = radius.Bytes(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func SecondaryHomeAgent_GetStrings(p *radius.Packet) (values []string, err error) {
	var i string
	for _, attr := range _Alcatel_GetsVendor(p, 13) {
		i = radius.String(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func SecondaryHomeAgent_Lookup(p *radius.Packet) (value []byte, err error) {
	a, ok := _Alcatel_LookupVendor(p, 13)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.Bytes(a)
	return
}

func SecondaryHomeAgent_LookupString(p *radius.Packet) (value string, err error) {
	a, ok := _Alcatel_LookupVendor(p, 13)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.String(a)
	return
}

func SecondaryHomeAgent_Set(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Alcatel_SetVendor(p, 13, a)
}

func SecondaryHomeAgent_SetString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Alcatel_SetVendor(p, 13, a)
}

func SecondaryHomeAgent_Del(p *radius.Packet) {
	_Alcatel_DelVendor(p, 13)
}

func HomeAgentPassword_Add(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Alcatel_AddVendor(p, 14, a)
}

func HomeAgentPassword_AddString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Alcatel_AddVendor(p, 14, a)
}

func HomeAgentPassword_Get(p *radius.Packet) (value []byte) {
	value, _ = HomeAgentPassword_Lookup(p)
	return
}

func HomeAgentPassword_GetString(p *radius.Packet) (value string) {
	value, _ = HomeAgentPassword_LookupString(p)
	return
}

func HomeAgentPassword_Gets(p *radius.Packet) (values [][]byte, err error) {
	var i []byte
	for _, attr := range _Alcatel_GetsVendor(p, 14) {
		i = radius.Bytes(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func HomeAgentPassword_GetStrings(p *radius.Packet) (values []string, err error) {
	var i string
	for _, attr := range _Alcatel_GetsVendor(p, 14) {
		i = radius.String(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func HomeAgentPassword_Lookup(p *radius.Packet) (value []byte, err error) {
	a, ok := _Alcatel_LookupVendor(p, 14)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.Bytes(a)
	return
}

func HomeAgentPassword_LookupString(p *radius.Packet) (value string, err error) {
	a, ok := _Alcatel_LookupVendor(p, 14)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.String(a)
	return
}

func HomeAgentPassword_Set(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Alcatel_SetVendor(p, 14, a)
}

func HomeAgentPassword_SetString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Alcatel_SetVendor(p, 14, a)
}

func HomeAgentPassword_Del(p *radius.Packet) {
	_Alcatel_DelVendor(p, 14)
}

func HomeNetworkName_Add(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Alcatel_AddVendor(p, 15, a)
}

func HomeNetworkName_AddString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Alcatel_AddVendor(p, 15, a)
}

func HomeNetworkName_Get(p *radius.Packet) (value []byte) {
	value, _ = HomeNetworkName_Lookup(p)
	return
}

func HomeNetworkName_GetString(p *radius.Packet) (value string) {
	value, _ = HomeNetworkName_LookupString(p)
	return
}

func HomeNetworkName_Gets(p *radius.Packet) (values [][]byte, err error) {
	var i []byte
	for _, attr := range _Alcatel_GetsVendor(p, 15) {
		i = radius.Bytes(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func HomeNetworkName_GetStrings(p *radius.Packet) (values []string, err error) {
	var i string
	for _, attr := range _Alcatel_GetsVendor(p, 15) {
		i = radius.String(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func HomeNetworkName_Lookup(p *radius.Packet) (value []byte, err error) {
	a, ok := _Alcatel_LookupVendor(p, 15)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.Bytes(a)
	return
}

func HomeNetworkName_LookupString(p *radius.Packet) (value string, err error) {
	a, ok := _Alcatel_LookupVendor(p, 15)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.String(a)
	return
}

func HomeNetworkName_Set(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Alcatel_SetVendor(p, 15, a)
}

func HomeNetworkName_SetString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Alcatel_SetVendor(p, 15, a)
}

func HomeNetworkName_Del(p *radius.Packet) {
	_Alcatel_DelVendor(p, 15)
}

type HomeAgentUDPPort uint32

var HomeAgentUDPPort_Strings = map[HomeAgentUDPPort]string{}

func (a HomeAgentUDPPort) String() string {
	if str, ok := HomeAgentUDPPort_Strings[a]; ok {
		return str
	}
	return "HomeAgentUDPPort(" + strconv.FormatUint(uint64(a), 10) + ")"
}

func HomeAgentUDPPort_Add(p *radius.Packet, value HomeAgentUDPPort) (err error) {
	a := radius.NewInteger(uint32(value))
	return _Alcatel_AddVendor(p, 16, a)
}

func HomeAgentUDPPort_Get(p *radius.Packet) (value HomeAgentUDPPort) {
	value, _ = HomeAgentUDPPort_Lookup(p)
	return
}

func HomeAgentUDPPort_Gets(p *radius.Packet) (values []HomeAgentUDPPort, err error) {
	var i uint32
	for _, attr := range _Alcatel_GetsVendor(p, 16) {
		i, err = radius.Integer(attr)
		if err != nil {
			return
		}
		values = append(values, HomeAgentUDPPort(i))
	}
	return
}

func HomeAgentUDPPort_Lookup(p *radius.Packet) (value HomeAgentUDPPort, err error) {
	a, ok := _Alcatel_LookupVendor(p, 16)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	var i uint32
	i, err = radius.Integer(a)
	if err != nil {
		return
	}
	value = HomeAgentUDPPort(i)
	return
}

func HomeAgentUDPPort_Set(p *radius.Packet, value HomeAgentUDPPort) (err error) {
	a := radius.NewInteger(uint32(value))
	return _Alcatel_SetVendor(p, 16, a)
}

func HomeAgentUDPPort_Del(p *radius.Packet) {
	_Alcatel_DelVendor(p, 16)
}

func IPDirect_Add(p *radius.Packet, value net.IP) (err error) {
	var a radius.Attribute
	a, err = radius.NewIPAddr(value)
	if err != nil {
		return
	}
	return _Alcatel_AddVendor(p, 17, a)
}

func IPDirect_Get(p *radius.Packet) (value net.IP) {
	value, _ = IPDirect_Lookup(p)
	return
}

func IPDirect_Gets(p *radius.Packet) (values []net.IP, err error) {
	var i net.IP
	for _, attr := range _Alcatel_GetsVendor(p, 17) {
		i, err = radius.IPAddr(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func IPDirect_Lookup(p *radius.Packet) (value net.IP, err error) {
	a, ok := _Alcatel_LookupVendor(p, 17)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value, err = radius.IPAddr(a)
	return
}

func IPDirect_Set(p *radius.Packet, value net.IP) (err error) {
	var a radius.Attribute
	a, err = radius.NewIPAddr(value)
	if err != nil {
		return
	}
	return _Alcatel_SetVendor(p, 17, a)
}

func IPDirect_Del(p *radius.Packet) {
	_Alcatel_DelVendor(p, 17)
}

type FRDirect uint32

const (
	FRDirect_Value_No  FRDirect = 0
	FRDirect_Value_Yes FRDirect = 1
)

var FRDirect_Strings = map[FRDirect]string{
	FRDirect_Value_No:  "No",
	FRDirect_Value_Yes: "Yes",
}

func (a FRDirect) String() string {
	if str, ok := FRDirect_Strings[a]; ok {
		return str
	}
	return "FRDirect(" + strconv.FormatUint(uint64(a), 10) + ")"
}

func FRDirect_Add(p *radius.Packet, value FRDirect) (err error) {
	a := radius.NewInteger(uint32(value))
	return _Alcatel_AddVendor(p, 18, a)
}

func FRDirect_Get(p *radius.Packet) (value FRDirect) {
	value, _ = FRDirect_Lookup(p)
	return
}

func FRDirect_Gets(p *radius.Packet) (values []FRDirect, err error) {
	var i uint32
	for _, attr := range _Alcatel_GetsVendor(p, 18) {
		i, err = radius.Integer(attr)
		if err != nil {
			return
		}
		values = append(values, FRDirect(i))
	}
	return
}

func FRDirect_Lookup(p *radius.Packet) (value FRDirect, err error) {
	a, ok := _Alcatel_LookupVendor(p, 18)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	var i uint32
	i, err = radius.Integer(a)
	if err != nil {
		return
	}
	value = FRDirect(i)
	return
}

func FRDirect_Set(p *radius.Packet, value FRDirect) (err error) {
	a := radius.NewInteger(uint32(value))
	return _Alcatel_SetVendor(p, 18, a)
}

func FRDirect_Del(p *radius.Packet) {
	_Alcatel_DelVendor(p, 18)
}

func FRDirectProfile_Add(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Alcatel_AddVendor(p, 19, a)
}

func FRDirectProfile_AddString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Alcatel_AddVendor(p, 19, a)
}

func FRDirectProfile_Get(p *radius.Packet) (value []byte) {
	value, _ = FRDirectProfile_Lookup(p)
	return
}

func FRDirectProfile_GetString(p *radius.Packet) (value string) {
	value, _ = FRDirectProfile_LookupString(p)
	return
}

func FRDirectProfile_Gets(p *radius.Packet) (values [][]byte, err error) {
	var i []byte
	for _, attr := range _Alcatel_GetsVendor(p, 19) {
		i = radius.Bytes(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func FRDirectProfile_GetStrings(p *radius.Packet) (values []string, err error) {
	var i string
	for _, attr := range _Alcatel_GetsVendor(p, 19) {
		i = radius.String(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func FRDirectProfile_Lookup(p *radius.Packet) (value []byte, err error) {
	a, ok := _Alcatel_LookupVendor(p, 19)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.Bytes(a)
	return
}

func FRDirectProfile_LookupString(p *radius.Packet) (value string, err error) {
	a, ok := _Alcatel_LookupVendor(p, 19)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.String(a)
	return
}

func FRDirectProfile_Set(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Alcatel_SetVendor(p, 19, a)
}

func FRDirectProfile_SetString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Alcatel_SetVendor(p, 19, a)
}

func FRDirectProfile_Del(p *radius.Packet) {
	_Alcatel_DelVendor(p, 19)
}

type FRDirectDLCI uint32

var FRDirectDLCI_Strings = map[FRDirectDLCI]string{}

func (a FRDirectDLCI) String() string {
	if str, ok := FRDirectDLCI_Strings[a]; ok {
		return str
	}
	return "FRDirectDLCI(" + strconv.FormatUint(uint64(a), 10) + ")"
}

func FRDirectDLCI_Add(p *radius.Packet, value FRDirectDLCI) (err error) {
	a := radius.NewInteger(uint32(value))
	return _Alcatel_AddVendor(p, 20, a)
}

func FRDirectDLCI_Get(p *radius.Packet) (value FRDirectDLCI) {
	value, _ = FRDirectDLCI_Lookup(p)
	return
}

func FRDirectDLCI_Gets(p *radius.Packet) (values []FRDirectDLCI, err error) {
	var i uint32
	for _, attr := range _Alcatel_GetsVendor(p, 20) {
		i, err = radius.Integer(attr)
		if err != nil {
			return
		}
		values = append(values, FRDirectDLCI(i))
	}
	return
}

func FRDirectDLCI_Lookup(p *radius.Packet) (value FRDirectDLCI, err error) {
	a, ok := _Alcatel_LookupVendor(p, 20)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	var i uint32
	i, err = radius.Integer(a)
	if err != nil {
		return
	}
	value = FRDirectDLCI(i)
	return
}

func FRDirectDLCI_Set(p *radius.Packet, value FRDirectDLCI) (err error) {
	a := radius.NewInteger(uint32(value))
	return _Alcatel_SetVendor(p, 20, a)
}

func FRDirectDLCI_Del(p *radius.Packet) {
	_Alcatel_DelVendor(p, 20)
}

func ATMDirect_Add(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Alcatel_AddVendor(p, 21, a)
}

func ATMDirect_AddString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Alcatel_AddVendor(p, 21, a)
}

func ATMDirect_Get(p *radius.Packet) (value []byte) {
	value, _ = ATMDirect_Lookup(p)
	return
}

func ATMDirect_GetString(p *radius.Packet) (value string) {
	value, _ = ATMDirect_LookupString(p)
	return
}

func ATMDirect_Gets(p *radius.Packet) (values [][]byte, err error) {
	var i []byte
	for _, attr := range _Alcatel_GetsVendor(p, 21) {
		i = radius.Bytes(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func ATMDirect_GetStrings(p *radius.Packet) (values []string, err error) {
	var i string
	for _, attr := range _Alcatel_GetsVendor(p, 21) {
		i = radius.String(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func ATMDirect_Lookup(p *radius.Packet) (value []byte, err error) {
	a, ok := _Alcatel_LookupVendor(p, 21)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.Bytes(a)
	return
}

func ATMDirect_LookupString(p *radius.Packet) (value string, err error) {
	a, ok := _Alcatel_LookupVendor(p, 21)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.String(a)
	return
}

func ATMDirect_Set(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Alcatel_SetVendor(p, 21, a)
}

func ATMDirect_SetString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Alcatel_SetVendor(p, 21, a)
}

func ATMDirect_Del(p *radius.Packet) {
	_Alcatel_DelVendor(p, 21)
}

type IPTOS uint32

const (
	IPTOS_Value_IPTOSNormal      IPTOS = 0
	IPTOS_Value_IPTOSDisabled    IPTOS = 1
	IPTOS_Value_IPTOSCost        IPTOS = 2
	IPTOS_Value_IPTOSReliability IPTOS = 4
	IPTOS_Value_IPTOSThroughput  IPTOS = 8
	IPTOS_Value_IPTOSLatency     IPTOS = 16
)

var IPTOS_Strings = map[IPTOS]string{
	IPTOS_Value_IPTOSNormal:      "IP-TOS-Normal",
	IPTOS_Value_IPTOSDisabled:    "IP-TOS-Disabled",
	IPTOS_Value_IPTOSCost:        "IP-TOS-Cost",
	IPTOS_Value_IPTOSReliability: "IP-TOS-Reliability",
	IPTOS_Value_IPTOSThroughput:  "IP-TOS-Throughput",
	IPTOS_Value_IPTOSLatency:     "IP-TOS-Latency",
}

func (a IPTOS) String() string {
	if str, ok := IPTOS_Strings[a]; ok {
		return str
	}
	return "IPTOS(" + strconv.FormatUint(uint64(a), 10) + ")"
}

func IPTOS_Add(p *radius.Packet, value IPTOS) (err error) {
	a := radius.NewInteger(uint32(value))
	return _Alcatel_AddVendor(p, 22, a)
}

func IPTOS_Get(p *radius.Packet) (value IPTOS) {
	value, _ = IPTOS_Lookup(p)
	return
}

func IPTOS_Gets(p *radius.Packet) (values []IPTOS, err error) {
	var i uint32
	for _, attr := range _Alcatel_GetsVendor(p, 22) {
		i, err = radius.Integer(attr)
		if err != nil {
			return
		}
		values = append(values, IPTOS(i))
	}
	return
}

func IPTOS_Lookup(p *radius.Packet) (value IPTOS, err error) {
	a, ok := _Alcatel_LookupVendor(p, 22)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	var i uint32
	i, err = radius.Integer(a)
	if err != nil {
		return
	}
	value = IPTOS(i)
	return
}

func IPTOS_Set(p *radius.Packet, value IPTOS) (err error) {
	a := radius.NewInteger(uint32(value))
	return _Alcatel_SetVendor(p, 22, a)
}

func IPTOS_Del(p *radius.Packet) {
	_Alcatel_DelVendor(p, 22)
}

type IPTOSPrecedence uint32

const (
	IPTOSPrecedence_Value_IPTOSPrecedencePriNormal IPTOSPrecedence = 0
	IPTOSPrecedence_Value_IPTOSPrecedencePriOne    IPTOSPrecedence = 32
	IPTOSPrecedence_Value_IPTOSPrecedencePriTwo    IPTOSPrecedence = 64
	IPTOSPrecedence_Value_IPTOSPrecedencePriThree  IPTOSPrecedence = 96
	IPTOSPrecedence_Value_IPTOSPrecedencePriFour   IPTOSPrecedence = 128
	IPTOSPrecedence_Value_IPTOSPrecedencePriFive   IPTOSPrecedence = 160
	IPTOSPrecedence_Value_IPTOSPrecedencePriSix    IPTOSPrecedence = 192
	IPTOSPrecedence_Value_IPTOSPrecedencePriSeven  IPTOSPrecedence = 224
)

var IPTOSPrecedence_Strings = map[IPTOSPrecedence]string{
	IPTOSPrecedence_Value_IPTOSPrecedencePriNormal: "IP-TOS-Precedence-Pri-Normal",
	IPTOSPrecedence_Value_IPTOSPrecedencePriOne:    "IP-TOS-Precedence-Pri-One",
	IPTOSPrecedence_Value_IPTOSPrecedencePriTwo:    "IP-TOS-Precedence-Pri-Two",
	IPTOSPrecedence_Value_IPTOSPrecedencePriThree:  "IP-TOS-Precedence-Pri-Three",
	IPTOSPrecedence_Value_IPTOSPrecedencePriFour:   "IP-TOS-Precedence-Pri-Four",
	IPTOSPrecedence_Value_IPTOSPrecedencePriFive:   "IP-TOS-Precedence-Pri-Five",
	IPTOSPrecedence_Value_IPTOSPrecedencePriSix:    "IP-TOS-Precedence-Pri-Six",
	IPTOSPrecedence_Value_IPTOSPrecedencePriSeven:  "IP-TOS-Precedence-Pri-Seven",
}

func (a IPTOSPrecedence) String() string {
	if str, ok := IPTOSPrecedence_Strings[a]; ok {
		return str
	}
	return "IPTOSPrecedence(" + strconv.FormatUint(uint64(a), 10) + ")"
}

func IPTOSPrecedence_Add(p *radius.Packet, value IPTOSPrecedence) (err error) {
	a := radius.NewInteger(uint32(value))
	return _Alcatel_AddVendor(p, 23, a)
}

func IPTOSPrecedence_Get(p *radius.Packet) (value IPTOSPrecedence) {
	value, _ = IPTOSPrecedence_Lookup(p)
	return
}

func IPTOSPrecedence_Gets(p *radius.Packet) (values []IPTOSPrecedence, err error) {
	var i uint32
	for _, attr := range _Alcatel_GetsVendor(p, 23) {
		i, err = radius.Integer(attr)
		if err != nil {
			return
		}
		values = append(values, IPTOSPrecedence(i))
	}
	return
}

func IPTOSPrecedence_Lookup(p *radius.Packet) (value IPTOSPrecedence, err error) {
	a, ok := _Alcatel_LookupVendor(p, 23)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	var i uint32
	i, err = radius.Integer(a)
	if err != nil {
		return
	}
	value = IPTOSPrecedence(i)
	return
}

func IPTOSPrecedence_Set(p *radius.Packet, value IPTOSPrecedence) (err error) {
	a := radius.NewInteger(uint32(value))
	return _Alcatel_SetVendor(p, 23, a)
}

func IPTOSPrecedence_Del(p *radius.Packet) {
	_Alcatel_DelVendor(p, 23)
}

type IPTOSApplyTo uint32

const (
	IPTOSApplyTo_Value_IPTOSApplyToIncoming IPTOSApplyTo = 1024
	IPTOSApplyTo_Value_IPTOSApplyToOutgoing IPTOSApplyTo = 2048
	IPTOSApplyTo_Value_IPTOSApplyToBoth     IPTOSApplyTo = 3072
)

var IPTOSApplyTo_Strings = map[IPTOSApplyTo]string{
	IPTOSApplyTo_Value_IPTOSApplyToIncoming: "IP-TOS-Apply-To-Incoming",
	IPTOSApplyTo_Value_IPTOSApplyToOutgoing: "IP-TOS-Apply-To-Outgoing",
	IPTOSApplyTo_Value_IPTOSApplyToBoth:     "IP-TOS-Apply-To-Both",
}

func (a IPTOSApplyTo) String() string {
	if str, ok := IPTOSApplyTo_Strings[a]; ok {
		return str
	}
	return "IPTOSApplyTo(" + strconv.FormatUint(uint64(a), 10) + ")"
}

func IPTOSApplyTo_Add(p *radius.Packet, value IPTOSApplyTo) (err error) {
	a := radius.NewInteger(uint32(value))
	return _Alcatel_AddVendor(p, 24, a)
}

func IPTOSApplyTo_Get(p *radius.Packet) (value IPTOSApplyTo) {
	value, _ = IPTOSApplyTo_Lookup(p)
	return
}

func IPTOSApplyTo_Gets(p *radius.Packet) (values []IPTOSApplyTo, err error) {
	var i uint32
	for _, attr := range _Alcatel_GetsVendor(p, 24) {
		i, err = radius.Integer(attr)
		if err != nil {
			return
		}
		values = append(values, IPTOSApplyTo(i))
	}
	return
}

func IPTOSApplyTo_Lookup(p *radius.Packet) (value IPTOSApplyTo, err error) {
	a, ok := _Alcatel_LookupVendor(p, 24)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	var i uint32
	i, err = radius.Integer(a)
	if err != nil {
		return
	}
	value = IPTOSApplyTo(i)
	return
}

func IPTOSApplyTo_Set(p *radius.Packet, value IPTOSApplyTo) (err error) {
	a := radius.NewInteger(uint32(value))
	return _Alcatel_SetVendor(p, 24, a)
}

func IPTOSApplyTo_Del(p *radius.Packet) {
	_Alcatel_DelVendor(p, 24)
}

type MCastClient uint32

const (
	MCastClient_Value_MulticastNo  MCastClient = 0
	MCastClient_Value_MulticastYes MCastClient = 1
)

var MCastClient_Strings = map[MCastClient]string{
	MCastClient_Value_MulticastNo:  "Multicast-No",
	MCastClient_Value_MulticastYes: "Multicast-Yes",
}

func (a MCastClient) String() string {
	if str, ok := MCastClient_Strings[a]; ok {
		return str
	}
	return "MCastClient(" + strconv.FormatUint(uint64(a), 10) + ")"
}

func MCastClient_Add(p *radius.Packet, value MCastClient) (err error) {
	a := radius.NewInteger(uint32(value))
	return _Alcatel_AddVendor(p, 27, a)
}

func MCastClient_Get(p *radius.Packet) (value MCastClient) {
	value, _ = MCastClient_Lookup(p)
	return
}

func MCastClient_Gets(p *radius.Packet) (values []MCastClient, err error) {
	var i uint32
	for _, attr := range _Alcatel_GetsVendor(p, 27) {
		i, err = radius.Integer(attr)
		if err != nil {
			return
		}
		values = append(values, MCastClient(i))
	}
	return
}

func MCastClient_Lookup(p *radius.Packet) (value MCastClient, err error) {
	a, ok := _Alcatel_LookupVendor(p, 27)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	var i uint32
	i, err = radius.Integer(a)
	if err != nil {
		return
	}
	value = MCastClient(i)
	return
}

func MCastClient_Set(p *radius.Packet, value MCastClient) (err error) {
	a := radius.NewInteger(uint32(value))
	return _Alcatel_SetVendor(p, 27, a)
}

func MCastClient_Del(p *radius.Packet) {
	_Alcatel_DelVendor(p, 27)
}

type ModemPortNo uint32

var ModemPortNo_Strings = map[ModemPortNo]string{}

func (a ModemPortNo) String() string {
	if str, ok := ModemPortNo_Strings[a]; ok {
		return str
	}
	return "ModemPortNo(" + strconv.FormatUint(uint64(a), 10) + ")"
}

func ModemPortNo_Add(p *radius.Packet, value ModemPortNo) (err error) {
	a := radius.NewInteger(uint32(value))
	return _Alcatel_AddVendor(p, 28, a)
}

func ModemPortNo_Get(p *radius.Packet) (value ModemPortNo) {
	value, _ = ModemPortNo_Lookup(p)
	return
}

func ModemPortNo_Gets(p *radius.Packet) (values []ModemPortNo, err error) {
	var i uint32
	for _, attr := range _Alcatel_GetsVendor(p, 28) {
		i, err = radius.Integer(attr)
		if err != nil {
			return
		}
		values = append(values, ModemPortNo(i))
	}
	return
}

func ModemPortNo_Lookup(p *radius.Packet) (value ModemPortNo, err error) {
	a, ok := _Alcatel_LookupVendor(p, 28)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	var i uint32
	i, err = radius.Integer(a)
	if err != nil {
		return
	}
	value = ModemPortNo(i)
	return
}

func ModemPortNo_Set(p *radius.Packet, value ModemPortNo) (err error) {
	a := radius.NewInteger(uint32(value))
	return _Alcatel_SetVendor(p, 28, a)
}

func ModemPortNo_Del(p *radius.Packet) {
	_Alcatel_DelVendor(p, 28)
}

type ModemSlotNo uint32

var ModemSlotNo_Strings = map[ModemSlotNo]string{}

func (a ModemSlotNo) String() string {
	if str, ok := ModemSlotNo_Strings[a]; ok {
		return str
	}
	return "ModemSlotNo(" + strconv.FormatUint(uint64(a), 10) + ")"
}

func ModemSlotNo_Add(p *radius.Packet, value ModemSlotNo) (err error) {
	a := radius.NewInteger(uint32(value))
	return _Alcatel_AddVendor(p, 29, a)
}

func ModemSlotNo_Get(p *radius.Packet) (value ModemSlotNo) {
	value, _ = ModemSlotNo_Lookup(p)
	return
}

func ModemSlotNo_Gets(p *radius.Packet) (values []ModemSlotNo, err error) {
	var i uint32
	for _, attr := range _Alcatel_GetsVendor(p, 29) {
		i, err = radius.Integer(attr)
		if err != nil {
			return
		}
		values = append(values, ModemSlotNo(i))
	}
	return
}

func ModemSlotNo_Lookup(p *radius.Packet) (value ModemSlotNo, err error) {
	a, ok := _Alcatel_LookupVendor(p, 29)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	var i uint32
	i, err = radius.Integer(a)
	if err != nil {
		return
	}
	value = ModemSlotNo(i)
	return
}

func ModemSlotNo_Set(p *radius.Packet, value ModemSlotNo) (err error) {
	a := radius.NewInteger(uint32(value))
	return _Alcatel_SetVendor(p, 29, a)
}

func ModemSlotNo_Del(p *radius.Packet) {
	_Alcatel_DelVendor(p, 29)
}

type ModemShelfNo uint32

var ModemShelfNo_Strings = map[ModemShelfNo]string{}

func (a ModemShelfNo) String() string {
	if str, ok := ModemShelfNo_Strings[a]; ok {
		return str
	}
	return "ModemShelfNo(" + strconv.FormatUint(uint64(a), 10) + ")"
}

func ModemShelfNo_Add(p *radius.Packet, value ModemShelfNo) (err error) {
	a := radius.NewInteger(uint32(value))
	return _Alcatel_AddVendor(p, 30, a)
}

func ModemShelfNo_Get(p *radius.Packet) (value ModemShelfNo) {
	value, _ = ModemShelfNo_Lookup(p)
	return
}

func ModemShelfNo_Gets(p *radius.Packet) (values []ModemShelfNo, err error) {
	var i uint32
	for _, attr := range _Alcatel_GetsVendor(p, 30) {
		i, err = radius.Integer(attr)
		if err != nil {
			return
		}
		values = append(values, ModemShelfNo(i))
	}
	return
}

func ModemShelfNo_Lookup(p *radius.Packet) (value ModemShelfNo, err error) {
	a, ok := _Alcatel_LookupVendor(p, 30)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	var i uint32
	i, err = radius.Integer(a)
	if err != nil {
		return
	}
	value = ModemShelfNo(i)
	return
}

func ModemShelfNo_Set(p *radius.Packet, value ModemShelfNo) (err error) {
	a := radius.NewInteger(uint32(value))
	return _Alcatel_SetVendor(p, 30, a)
}

func ModemShelfNo_Del(p *radius.Packet) {
	_Alcatel_DelVendor(p, 30)
}

func Filter_Add(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Alcatel_AddVendor(p, 60, a)
}

func Filter_AddString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Alcatel_AddVendor(p, 60, a)
}

func Filter_Get(p *radius.Packet) (value []byte) {
	value, _ = Filter_Lookup(p)
	return
}

func Filter_GetString(p *radius.Packet) (value string) {
	value, _ = Filter_LookupString(p)
	return
}

func Filter_Gets(p *radius.Packet) (values [][]byte, err error) {
	var i []byte
	for _, attr := range _Alcatel_GetsVendor(p, 60) {
		i = radius.Bytes(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func Filter_GetStrings(p *radius.Packet) (values []string, err error) {
	var i string
	for _, attr := range _Alcatel_GetsVendor(p, 60) {
		i = radius.String(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func Filter_Lookup(p *radius.Packet) (value []byte, err error) {
	a, ok := _Alcatel_LookupVendor(p, 60)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.Bytes(a)
	return
}

func Filter_LookupString(p *radius.Packet) (value string, err error) {
	a, ok := _Alcatel_LookupVendor(p, 60)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.String(a)
	return
}

func Filter_Set(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Alcatel_SetVendor(p, 60, a)
}

func Filter_SetString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Alcatel_SetVendor(p, 60, a)
}

func Filter_Del(p *radius.Packet) {
	_Alcatel_DelVendor(p, 60)
}

func VrouterName_Add(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Alcatel_AddVendor(p, 61, a)
}

func VrouterName_AddString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Alcatel_AddVendor(p, 61, a)
}

func VrouterName_Get(p *radius.Packet) (value []byte) {
	value, _ = VrouterName_Lookup(p)
	return
}

func VrouterName_GetString(p *radius.Packet) (value string) {
	value, _ = VrouterName_LookupString(p)
	return
}

func VrouterName_Gets(p *radius.Packet) (values [][]byte, err error) {
	var i []byte
	for _, attr := range _Alcatel_GetsVendor(p, 61) {
		i = radius.Bytes(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func VrouterName_GetStrings(p *radius.Packet) (values []string, err error) {
	var i string
	for _, attr := range _Alcatel_GetsVendor(p, 61) {
		i = radius.String(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func VrouterName_Lookup(p *radius.Packet) (value []byte, err error) {
	a, ok := _Alcatel_LookupVendor(p, 61)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.Bytes(a)
	return
}

func VrouterName_LookupString(p *radius.Packet) (value string, err error) {
	a, ok := _Alcatel_LookupVendor(p, 61)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.String(a)
	return
}

func VrouterName_Set(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Alcatel_SetVendor(p, 61, a)
}

func VrouterName_SetString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Alcatel_SetVendor(p, 61, a)
}

func VrouterName_Del(p *radius.Packet) {
	_Alcatel_DelVendor(p, 61)
}

type RequireAuth uint32

const (
	RequireAuth_Value_NotRequireAuth RequireAuth = 0
	RequireAuth_Value_RequireAuth    RequireAuth = 1
)

var RequireAuth_Strings = map[RequireAuth]string{
	RequireAuth_Value_NotRequireAuth: "Not-Require-Auth",
	RequireAuth_Value_RequireAuth:    "Require-Auth",
}

func (a RequireAuth) String() string {
	if str, ok := RequireAuth_Strings[a]; ok {
		return str
	}
	return "RequireAuth(" + strconv.FormatUint(uint64(a), 10) + ")"
}

func RequireAuth_Add(p *radius.Packet, value RequireAuth) (err error) {
	a := radius.NewInteger(uint32(value))
	return _Alcatel_AddVendor(p, 62, a)
}

func RequireAuth_Get(p *radius.Packet) (value RequireAuth) {
	value, _ = RequireAuth_Lookup(p)
	return
}

func RequireAuth_Gets(p *radius.Packet) (values []RequireAuth, err error) {
	var i uint32
	for _, attr := range _Alcatel_GetsVendor(p, 62) {
		i, err = radius.Integer(attr)
		if err != nil {
			return
		}
		values = append(values, RequireAuth(i))
	}
	return
}

func RequireAuth_Lookup(p *radius.Packet) (value RequireAuth, err error) {
	a, ok := _Alcatel_LookupVendor(p, 62)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	var i uint32
	i, err = radius.Integer(a)
	if err != nil {
		return
	}
	value = RequireAuth(i)
	return
}

func RequireAuth_Set(p *radius.Packet, value RequireAuth) (err error) {
	a := radius.NewInteger(uint32(value))
	return _Alcatel_SetVendor(p, 62, a)
}

func RequireAuth_Del(p *radius.Packet) {
	_Alcatel_DelVendor(p, 62)
}

func IPPoolDefinition_Add(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Alcatel_AddVendor(p, 63, a)
}

func IPPoolDefinition_AddString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Alcatel_AddVendor(p, 63, a)
}

func IPPoolDefinition_Get(p *radius.Packet) (value []byte) {
	value, _ = IPPoolDefinition_Lookup(p)
	return
}

func IPPoolDefinition_GetString(p *radius.Packet) (value string) {
	value, _ = IPPoolDefinition_LookupString(p)
	return
}

func IPPoolDefinition_Gets(p *radius.Packet) (values [][]byte, err error) {
	var i []byte
	for _, attr := range _Alcatel_GetsVendor(p, 63) {
		i = radius.Bytes(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func IPPoolDefinition_GetStrings(p *radius.Packet) (values []string, err error) {
	var i string
	for _, attr := range _Alcatel_GetsVendor(p, 63) {
		i = radius.String(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func IPPoolDefinition_Lookup(p *radius.Packet) (value []byte, err error) {
	a, ok := _Alcatel_LookupVendor(p, 63)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.Bytes(a)
	return
}

func IPPoolDefinition_LookupString(p *radius.Packet) (value string, err error) {
	a, ok := _Alcatel_LookupVendor(p, 63)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.String(a)
	return
}

func IPPoolDefinition_Set(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Alcatel_SetVendor(p, 63, a)
}

func IPPoolDefinition_SetString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Alcatel_SetVendor(p, 63, a)
}

func IPPoolDefinition_Del(p *radius.Packet) {
	_Alcatel_DelVendor(p, 63)
}

type AssignIPPool uint32

var AssignIPPool_Strings = map[AssignIPPool]string{}

func (a AssignIPPool) String() string {
	if str, ok := AssignIPPool_Strings[a]; ok {
		return str
	}
	return "AssignIPPool(" + strconv.FormatUint(uint64(a), 10) + ")"
}

func AssignIPPool_Add(p *radius.Packet, value AssignIPPool) (err error) {
	a := radius.NewInteger(uint32(value))
	return _Alcatel_AddVendor(p, 64, a)
}

func AssignIPPool_Get(p *radius.Packet) (value AssignIPPool) {
	value, _ = AssignIPPool_Lookup(p)
	return
}

func AssignIPPool_Gets(p *radius.Packet) (values []AssignIPPool, err error) {
	var i uint32
	for _, attr := range _Alcatel_GetsVendor(p, 64) {
		i, err = radius.Integer(attr)
		if err != nil {
			return
		}
		values = append(values, AssignIPPool(i))
	}
	return
}

func AssignIPPool_Lookup(p *radius.Packet) (value AssignIPPool, err error) {
	a, ok := _Alcatel_LookupVendor(p, 64)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	var i uint32
	i, err = radius.Integer(a)
	if err != nil {
		return
	}
	value = AssignIPPool(i)
	return
}

func AssignIPPool_Set(p *radius.Packet, value AssignIPPool) (err error) {
	a := radius.NewInteger(uint32(value))
	return _Alcatel_SetVendor(p, 64, a)
}

func AssignIPPool_Del(p *radius.Packet) {
	_Alcatel_DelVendor(p, 64)
}

func DataFilter_Add(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Alcatel_AddVendor(p, 65, a)
}

func DataFilter_AddString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Alcatel_AddVendor(p, 65, a)
}

func DataFilter_Get(p *radius.Packet) (value []byte) {
	value, _ = DataFilter_Lookup(p)
	return
}

func DataFilter_GetString(p *radius.Packet) (value string) {
	value, _ = DataFilter_LookupString(p)
	return
}

func DataFilter_Gets(p *radius.Packet) (values [][]byte, err error) {
	var i []byte
	for _, attr := range _Alcatel_GetsVendor(p, 65) {
		i = radius.Bytes(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func DataFilter_GetStrings(p *radius.Packet) (values []string, err error) {
	var i string
	for _, attr := range _Alcatel_GetsVendor(p, 65) {
		i = radius.String(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func DataFilter_Lookup(p *radius.Packet) (value []byte, err error) {
	a, ok := _Alcatel_LookupVendor(p, 65)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.Bytes(a)
	return
}

func DataFilter_LookupString(p *radius.Packet) (value string, err error) {
	a, ok := _Alcatel_LookupVendor(p, 65)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.String(a)
	return
}

func DataFilter_Set(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Alcatel_SetVendor(p, 65, a)
}

func DataFilter_SetString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Alcatel_SetVendor(p, 65, a)
}

func DataFilter_Del(p *radius.Packet) {
	_Alcatel_DelVendor(p, 65)
}

type SourceIPCheck uint32

const (
	SourceIPCheck_Value_SourceIPCheckNo  SourceIPCheck = 0
	SourceIPCheck_Value_SourceIPCheckYes SourceIPCheck = 1
)

var SourceIPCheck_Strings = map[SourceIPCheck]string{
	SourceIPCheck_Value_SourceIPCheckNo:  "Source-IP-Check-No",
	SourceIPCheck_Value_SourceIPCheckYes: "Source-IP-Check-Yes",
}

func (a SourceIPCheck) String() string {
	if str, ok := SourceIPCheck_Strings[a]; ok {
		return str
	}
	return "SourceIPCheck(" + strconv.FormatUint(uint64(a), 10) + ")"
}

func SourceIPCheck_Add(p *radius.Packet, value SourceIPCheck) (err error) {
	a := radius.NewInteger(uint32(value))
	return _Alcatel_AddVendor(p, 66, a)
}

func SourceIPCheck_Get(p *radius.Packet) (value SourceIPCheck) {
	value, _ = SourceIPCheck_Lookup(p)
	return
}

func SourceIPCheck_Gets(p *radius.Packet) (values []SourceIPCheck, err error) {
	var i uint32
	for _, attr := range _Alcatel_GetsVendor(p, 66) {
		i, err = radius.Integer(attr)
		if err != nil {
			return
		}
		values = append(values, SourceIPCheck(i))
	}
	return
}

func SourceIPCheck_Lookup(p *radius.Packet) (value SourceIPCheck, err error) {
	a, ok := _Alcatel_LookupVendor(p, 66)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	var i uint32
	i, err = radius.Integer(a)
	if err != nil {
		return
	}
	value = SourceIPCheck(i)
	return
}

func SourceIPCheck_Set(p *radius.Packet, value SourceIPCheck) (err error) {
	a := radius.NewInteger(uint32(value))
	return _Alcatel_SetVendor(p, 66, a)
}

func SourceIPCheck_Del(p *radius.Packet) {
	_Alcatel_DelVendor(p, 66)
}

func ModemAnswerString_Add(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Alcatel_AddVendor(p, 67, a)
}

func ModemAnswerString_AddString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Alcatel_AddVendor(p, 67, a)
}

func ModemAnswerString_Get(p *radius.Packet) (value []byte) {
	value, _ = ModemAnswerString_Lookup(p)
	return
}

func ModemAnswerString_GetString(p *radius.Packet) (value string) {
	value, _ = ModemAnswerString_LookupString(p)
	return
}

func ModemAnswerString_Gets(p *radius.Packet) (values [][]byte, err error) {
	var i []byte
	for _, attr := range _Alcatel_GetsVendor(p, 67) {
		i = radius.Bytes(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func ModemAnswerString_GetStrings(p *radius.Packet) (values []string, err error) {
	var i string
	for _, attr := range _Alcatel_GetsVendor(p, 67) {
		i = radius.String(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func ModemAnswerString_Lookup(p *radius.Packet) (value []byte, err error) {
	a, ok := _Alcatel_LookupVendor(p, 67)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.Bytes(a)
	return
}

func ModemAnswerString_LookupString(p *radius.Packet) (value string, err error) {
	a, ok := _Alcatel_LookupVendor(p, 67)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.String(a)
	return
}

func ModemAnswerString_Set(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Alcatel_SetVendor(p, 67, a)
}

func ModemAnswerString_SetString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Alcatel_SetVendor(p, 67, a)
}

func ModemAnswerString_Del(p *radius.Packet) {
	_Alcatel_DelVendor(p, 67)
}

type AuthType uint32

const (
	AuthType_Value_AuthNone    AuthType = 0
	AuthType_Value_AuthDefault AuthType = 1
	AuthType_Value_AuthAny     AuthType = 2
	AuthType_Value_AuthPAP     AuthType = 3
	AuthType_Value_AuthCHAP    AuthType = 4
	AuthType_Value_AuthMSCHAP  AuthType = 5
)

var AuthType_Strings = map[AuthType]string{
	AuthType_Value_AuthNone:    "Auth-None",
	AuthType_Value_AuthDefault: "Auth-Default",
	AuthType_Value_AuthAny:     "Auth-Any",
	AuthType_Value_AuthPAP:     "Auth-PAP",
	AuthType_Value_AuthCHAP:    "Auth-CHAP",
	AuthType_Value_AuthMSCHAP:  "Auth-MS-CHAP",
}

func (a AuthType) String() string {
	if str, ok := AuthType_Strings[a]; ok {
		return str
	}
	return "AuthType(" + strconv.FormatUint(uint64(a), 10) + ")"
}

func AuthType_Add(p *radius.Packet, value AuthType) (err error) {
	a := radius.NewInteger(uint32(value))
	return _Alcatel_AddVendor(p, 68, a)
}

func AuthType_Get(p *radius.Packet) (value AuthType) {
	value, _ = AuthType_Lookup(p)
	return
}

func AuthType_Gets(p *radius.Packet) (values []AuthType, err error) {
	var i uint32
	for _, attr := range _Alcatel_GetsVendor(p, 68) {
		i, err = radius.Integer(attr)
		if err != nil {
			return
		}
		values = append(values, AuthType(i))
	}
	return
}

func AuthType_Lookup(p *radius.Packet) (value AuthType, err error) {
	a, ok := _Alcatel_LookupVendor(p, 68)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	var i uint32
	i, err = radius.Integer(a)
	if err != nil {
		return
	}
	value = AuthType(i)
	return
}

func AuthType_Set(p *radius.Packet, value AuthType) (err error) {
	a := radius.NewInteger(uint32(value))
	return _Alcatel_SetVendor(p, 68, a)
}

func AuthType_Del(p *radius.Packet) {
	_Alcatel_DelVendor(p, 68)
}

type Qos uint32

var Qos_Strings = map[Qos]string{}

func (a Qos) String() string {
	if str, ok := Qos_Strings[a]; ok {
		return str
	}
	return "Qos(" + strconv.FormatUint(uint64(a), 10) + ")"
}

func Qos_Add(p *radius.Packet, value Qos) (err error) {
	a := radius.NewInteger(uint32(value))
	return _Alcatel_AddVendor(p, 70, a)
}

func Qos_Get(p *radius.Packet) (value Qos) {
	value, _ = Qos_Lookup(p)
	return
}

func Qos_Gets(p *radius.Packet) (values []Qos, err error) {
	var i uint32
	for _, attr := range _Alcatel_GetsVendor(p, 70) {
		i, err = radius.Integer(attr)
		if err != nil {
			return
		}
		values = append(values, Qos(i))
	}
	return
}

func Qos_Lookup(p *radius.Packet) (value Qos, err error) {
	a, ok := _Alcatel_LookupVendor(p, 70)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	var i uint32
	i, err = radius.Integer(a)
	if err != nil {
		return
	}
	value = Qos(i)
	return
}

func Qos_Set(p *radius.Packet, value Qos) (err error) {
	a := radius.NewInteger(uint32(value))
	return _Alcatel_SetVendor(p, 70, a)
}

func Qos_Del(p *radius.Packet) {
	_Alcatel_DelVendor(p, 70)
}

type Qoa uint32

var Qoa_Strings = map[Qoa]string{}

func (a Qoa) String() string {
	if str, ok := Qoa_Strings[a]; ok {
		return str
	}
	return "Qoa(" + strconv.FormatUint(uint64(a), 10) + ")"
}

func Qoa_Add(p *radius.Packet, value Qoa) (err error) {
	a := radius.NewInteger(uint32(value))
	return _Alcatel_AddVendor(p, 71, a)
}

func Qoa_Get(p *radius.Packet) (value Qoa) {
	value, _ = Qoa_Lookup(p)
	return
}

func Qoa_Gets(p *radius.Packet) (values []Qoa, err error) {
	var i uint32
	for _, attr := range _Alcatel_GetsVendor(p, 71) {
		i, err = radius.Integer(attr)
		if err != nil {
			return
		}
		values = append(values, Qoa(i))
	}
	return
}

func Qoa_Lookup(p *radius.Packet) (value Qoa, err error) {
	a, ok := _Alcatel_LookupVendor(p, 71)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	var i uint32
	i, err = radius.Integer(a)
	if err != nil {
		return
	}
	value = Qoa(i)
	return
}

func Qoa_Set(p *radius.Packet, value Qoa) (err error) {
	a := radius.NewInteger(uint32(value))
	return _Alcatel_SetVendor(p, 71, a)
}

func Qoa_Del(p *radius.Packet) {
	_Alcatel_DelVendor(p, 71)
}

type ClientAssignDNS uint32

const (
	ClientAssignDNS_Value_DNSAssignNo  ClientAssignDNS = 0
	ClientAssignDNS_Value_DNSAssignYes ClientAssignDNS = 1
)

var ClientAssignDNS_Strings = map[ClientAssignDNS]string{
	ClientAssignDNS_Value_DNSAssignNo:  "DNS-Assign-No",
	ClientAssignDNS_Value_DNSAssignYes: "DNS-Assign-Yes",
}

func (a ClientAssignDNS) String() string {
	if str, ok := ClientAssignDNS_Strings[a]; ok {
		return str
	}
	return "ClientAssignDNS(" + strconv.FormatUint(uint64(a), 10) + ")"
}

func ClientAssignDNS_Add(p *radius.Packet, value ClientAssignDNS) (err error) {
	a := radius.NewInteger(uint32(value))
	return _Alcatel_AddVendor(p, 72, a)
}

func ClientAssignDNS_Get(p *radius.Packet) (value ClientAssignDNS) {
	value, _ = ClientAssignDNS_Lookup(p)
	return
}

func ClientAssignDNS_Gets(p *radius.Packet) (values []ClientAssignDNS, err error) {
	var i uint32
	for _, attr := range _Alcatel_GetsVendor(p, 72) {
		i, err = radius.Integer(attr)
		if err != nil {
			return
		}
		values = append(values, ClientAssignDNS(i))
	}
	return
}

func ClientAssignDNS_Lookup(p *radius.Packet) (value ClientAssignDNS, err error) {
	a, ok := _Alcatel_LookupVendor(p, 72)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	var i uint32
	i, err = radius.Integer(a)
	if err != nil {
		return
	}
	value = ClientAssignDNS(i)
	return
}

func ClientAssignDNS_Set(p *radius.Packet, value ClientAssignDNS) (err error) {
	a := radius.NewInteger(uint32(value))
	return _Alcatel_SetVendor(p, 72, a)
}

func ClientAssignDNS_Del(p *radius.Packet) {
	_Alcatel_DelVendor(p, 72)
}

type ATMVPI uint32

var ATMVPI_Strings = map[ATMVPI]string{}

func (a ATMVPI) String() string {
	if str, ok := ATMVPI_Strings[a]; ok {
		return str
	}
	return "ATMVPI(" + strconv.FormatUint(uint64(a), 10) + ")"
}

func ATMVPI_Add(p *radius.Packet, value ATMVPI) (err error) {
	a := radius.NewInteger(uint32(value))
	return _Alcatel_AddVendor(p, 128, a)
}

func ATMVPI_Get(p *radius.Packet) (value ATMVPI) {
	value, _ = ATMVPI_Lookup(p)
	return
}

func ATMVPI_Gets(p *radius.Packet) (values []ATMVPI, err error) {
	var i uint32
	for _, attr := range _Alcatel_GetsVendor(p, 128) {
		i, err = radius.Integer(attr)
		if err != nil {
			return
		}
		values = append(values, ATMVPI(i))
	}
	return
}

func ATMVPI_Lookup(p *radius.Packet) (value ATMVPI, err error) {
	a, ok := _Alcatel_LookupVendor(p, 128)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	var i uint32
	i, err = radius.Integer(a)
	if err != nil {
		return
	}
	value = ATMVPI(i)
	return
}

func ATMVPI_Set(p *radius.Packet, value ATMVPI) (err error) {
	a := radius.NewInteger(uint32(value))
	return _Alcatel_SetVendor(p, 128, a)
}

func ATMVPI_Del(p *radius.Packet) {
	_Alcatel_DelVendor(p, 128)
}

type ATMVCI uint32

var ATMVCI_Strings = map[ATMVCI]string{}

func (a ATMVCI) String() string {
	if str, ok := ATMVCI_Strings[a]; ok {
		return str
	}
	return "ATMVCI(" + strconv.FormatUint(uint64(a), 10) + ")"
}

func ATMVCI_Add(p *radius.Packet, value ATMVCI) (err error) {
	a := radius.NewInteger(uint32(value))
	return _Alcatel_AddVendor(p, 129, a)
}

func ATMVCI_Get(p *radius.Packet) (value ATMVCI) {
	value, _ = ATMVCI_Lookup(p)
	return
}

func ATMVCI_Gets(p *radius.Packet) (values []ATMVCI, err error) {
	var i uint32
	for _, attr := range _Alcatel_GetsVendor(p, 129) {
		i, err = radius.Integer(attr)
		if err != nil {
			return
		}
		values = append(values, ATMVCI(i))
	}
	return
}

func ATMVCI_Lookup(p *radius.Packet) (value ATMVCI, err error) {
	a, ok := _Alcatel_LookupVendor(p, 129)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	var i uint32
	i, err = radius.Integer(a)
	if err != nil {
		return
	}
	value = ATMVCI(i)
	return
}

func ATMVCI_Set(p *radius.Packet, value ATMVCI) (err error) {
	a := radius.NewInteger(uint32(value))
	return _Alcatel_SetVendor(p, 129, a)
}

func ATMVCI_Del(p *radius.Packet) {
	_Alcatel_DelVendor(p, 129)
}

type InputOctetsDiff uint32

var InputOctetsDiff_Strings = map[InputOctetsDiff]string{}

func (a InputOctetsDiff) String() string {
	if str, ok := InputOctetsDiff_Strings[a]; ok {
		return str
	}
	return "InputOctetsDiff(" + strconv.FormatUint(uint64(a), 10) + ")"
}

func InputOctetsDiff_Add(p *radius.Packet, value InputOctetsDiff) (err error) {
	a := radius.NewInteger(uint32(value))
	return _Alcatel_AddVendor(p, 130, a)
}

func InputOctetsDiff_Get(p *radius.Packet) (value InputOctetsDiff) {
	value, _ = InputOctetsDiff_Lookup(p)
	return
}

func InputOctetsDiff_Gets(p *radius.Packet) (values []InputOctetsDiff, err error) {
	var i uint32
	for _, attr := range _Alcatel_GetsVendor(p, 130) {
		i, err = radius.Integer(attr)
		if err != nil {
			return
		}
		values = append(values, InputOctetsDiff(i))
	}
	return
}

func InputOctetsDiff_Lookup(p *radius.Packet) (value InputOctetsDiff, err error) {
	a, ok := _Alcatel_LookupVendor(p, 130)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	var i uint32
	i, err = radius.Integer(a)
	if err != nil {
		return
	}
	value = InputOctetsDiff(i)
	return
}

func InputOctetsDiff_Set(p *radius.Packet, value InputOctetsDiff) (err error) {
	a := radius.NewInteger(uint32(value))
	return _Alcatel_SetVendor(p, 130, a)
}

func InputOctetsDiff_Del(p *radius.Packet) {
	_Alcatel_DelVendor(p, 130)
}

type OutputOctetsDiff uint32

var OutputOctetsDiff_Strings = map[OutputOctetsDiff]string{}

func (a OutputOctetsDiff) String() string {
	if str, ok := OutputOctetsDiff_Strings[a]; ok {
		return str
	}
	return "OutputOctetsDiff(" + strconv.FormatUint(uint64(a), 10) + ")"
}

func OutputOctetsDiff_Add(p *radius.Packet, value OutputOctetsDiff) (err error) {
	a := radius.NewInteger(uint32(value))
	return _Alcatel_AddVendor(p, 131, a)
}

func OutputOctetsDiff_Get(p *radius.Packet) (value OutputOctetsDiff) {
	value, _ = OutputOctetsDiff_Lookup(p)
	return
}

func OutputOctetsDiff_Gets(p *radius.Packet) (values []OutputOctetsDiff, err error) {
	var i uint32
	for _, attr := range _Alcatel_GetsVendor(p, 131) {
		i, err = radius.Integer(attr)
		if err != nil {
			return
		}
		values = append(values, OutputOctetsDiff(i))
	}
	return
}

func OutputOctetsDiff_Lookup(p *radius.Packet) (value OutputOctetsDiff, err error) {
	a, ok := _Alcatel_LookupVendor(p, 131)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	var i uint32
	i, err = radius.Integer(a)
	if err != nil {
		return
	}
	value = OutputOctetsDiff(i)
	return
}

func OutputOctetsDiff_Set(p *radius.Packet, value OutputOctetsDiff) (err error) {
	a := radius.NewInteger(uint32(value))
	return _Alcatel_SetVendor(p, 131, a)
}

func OutputOctetsDiff_Del(p *radius.Packet) {
	_Alcatel_DelVendor(p, 131)
}

func UserMACAddress_Add(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Alcatel_AddVendor(p, 132, a)
}

func UserMACAddress_AddString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Alcatel_AddVendor(p, 132, a)
}

func UserMACAddress_Get(p *radius.Packet) (value []byte) {
	value, _ = UserMACAddress_Lookup(p)
	return
}

func UserMACAddress_GetString(p *radius.Packet) (value string) {
	value, _ = UserMACAddress_LookupString(p)
	return
}

func UserMACAddress_Gets(p *radius.Packet) (values [][]byte, err error) {
	var i []byte
	for _, attr := range _Alcatel_GetsVendor(p, 132) {
		i = radius.Bytes(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func UserMACAddress_GetStrings(p *radius.Packet) (values []string, err error) {
	var i string
	for _, attr := range _Alcatel_GetsVendor(p, 132) {
		i = radius.String(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func UserMACAddress_Lookup(p *radius.Packet) (value []byte, err error) {
	a, ok := _Alcatel_LookupVendor(p, 132)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.Bytes(a)
	return
}

func UserMACAddress_LookupString(p *radius.Packet) (value string, err error) {
	a, ok := _Alcatel_LookupVendor(p, 132)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.String(a)
	return
}

func UserMACAddress_Set(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Alcatel_SetVendor(p, 132, a)
}

func UserMACAddress_SetString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Alcatel_SetVendor(p, 132, a)
}

func UserMACAddress_Del(p *radius.Packet) {
	_Alcatel_DelVendor(p, 132)
}

func ATMTrafficProfile_Add(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Alcatel_AddVendor(p, 133, a)
}

func ATMTrafficProfile_AddString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Alcatel_AddVendor(p, 133, a)
}

func ATMTrafficProfile_Get(p *radius.Packet) (value []byte) {
	value, _ = ATMTrafficProfile_Lookup(p)
	return
}

func ATMTrafficProfile_GetString(p *radius.Packet) (value string) {
	value, _ = ATMTrafficProfile_LookupString(p)
	return
}

func ATMTrafficProfile_Gets(p *radius.Packet) (values [][]byte, err error) {
	var i []byte
	for _, attr := range _Alcatel_GetsVendor(p, 133) {
		i = radius.Bytes(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func ATMTrafficProfile_GetStrings(p *radius.Packet) (values []string, err error) {
	var i string
	for _, attr := range _Alcatel_GetsVendor(p, 133) {
		i = radius.String(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func ATMTrafficProfile_Lookup(p *radius.Packet) (value []byte, err error) {
	a, ok := _Alcatel_LookupVendor(p, 133)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.Bytes(a)
	return
}

func ATMTrafficProfile_LookupString(p *radius.Packet) (value string, err error) {
	a, ok := _Alcatel_LookupVendor(p, 133)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.String(a)
	return
}

func ATMTrafficProfile_Set(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Alcatel_SetVendor(p, 133, a)
}

func ATMTrafficProfile_SetString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Alcatel_SetVendor(p, 133, a)
}

func ATMTrafficProfile_Del(p *radius.Packet) {
	_Alcatel_DelVendor(p, 133)
}
